-- SYSX HUB v2.4 | All Fixed | Bring Mob + Logo + 4 Slider Stats
local Players=game:GetService("Players") local RS=game:GetService("ReplicatedStorage") local TS=game:GetService("TweenService") local UIS=game:GetService("UserInputService") local RS2=game:GetService("RunService") local WS=game:GetService("Workspace") local VU=game:GetService("VirtualUser") local TPS=game:GetService("TeleportService") local LT=game:GetService("Lighting") local HS=game:GetService("HttpService") local CS=game:GetService("CollectionService") local GS=game:GetService("GuiService") local P=Players.LocalPlayer local PG=P:WaitForChild("PlayerGui")
local function SafeParent()local ok,h=pcall(function()return gethui and gethui()end)if ok and h then return h end return PG end
local GP=SafeParent()
local Rem=RS:WaitForChild("Remotes",15) if not Rem then warn("No Remotes")return end
local CF=Rem:WaitForChild("CommF_",15) if not CF then warn("No CommF")return end
local MD=RS:FindFirstChild("Modules") local Net=MD and MD:FindFirstChild("Net")
repeat task.wait()until P.Character and P.Character:FindFirstChild("HumanoidRootPart")
local PID=game.PlaceId
local W1=(PID==2753915549 or PID==85211729168715)
local W2=(PID==4442272183 or PID==79091703265657)
local W3=(PID==7449423635 or PID==100117331123089)
local DC="https://discord.gg/xWa9NpFRr"
local BP={Color3.fromRGB(135,206,250),Color3.fromRGB(100,149,237),Color3.fromRGB(80,130,220),Color3.fromRGB(40,90,180),Color3.fromRGB(120,180,240)}
local T={BM=Color3.fromRGB(8,12,24),BS=Color3.fromRGB(16,22,40),BT=Color3.fromRGB(24,32,56),BH=Color3.fromRGB(32,44,76),BA=Color3.fromRGB(44,60,100),AB=Color3.fromRGB(180,220,255),TP=Color3.fromRGB(230,238,248),TS2=Color3.fromRGB(150,165,190),TM=Color3.fromRGB(105,118,145),BD=Color3.fromRGB(40,55,90),SB=Color3.fromRGB(60,130,220),SBS=Color3.fromRGB(180,220,255),TO=Color3.fromRGB(30,100,180),TF=Color3.fromRGB(55,60,80),TDO=Color3.fromRGB(255,255,255),TDF=Color3.fromRGB(180,185,200)}
local AR={}
local function RA(s)if s and s:IsA("UIStroke")then table.insert(AR,s)end end
local function Cr(c,p)local o=Instance.new(c)for k,v in pairs(p or{})do pcall(function()o[k]=v end)end return o end
local function Cn(p,r)local c=Instance.new("UICorner")c.CornerRadius=UDim.new(0,r or 10)c.Parent=p end
local function Sk(p,c,t,tr)local s=Instance.new("UIStroke")s.Color=c or T.BD s.Thickness=t or 1 s.Transparency=tr or 0.55 s.Parent=p return s end
local function TW(o,p,t)TS:Create(o,TweenInfo.new(t or 0.25,Enum.EasingStyle.Quart),p):Play()end
local function HRP()local c=P.Character return c and c:FindFirstChild("HumanoidRootPart")or nil end
local function Alive()local c=P.Character if not c then return false end local h=c:FindFirstChildOfClass("Humanoid")return h and h.Health>0 and c:FindFirstChild("HumanoidRootPart")~=nil end
local S={AutoFarm=false,AutoFarmNearest=false,AutoChest=false,AutoFarmMaterial=false,AutoFarmBones=false,AutoBoss=false,SelectedBoss=nil,SelectedMaterial=nil,SelectedWeapon="Melee",FastAttack=true,BringMob=true,BringRange=300,BringCount=2,AutoFarmSea=false,AutoStoreFruit=false,AutoBuyFruit=false,AutoFindFruit=false,AutoRaid=false,AutoAwaken=false,AutoCakePrince=false,AutoDoughKing=false,AutoEliteHunter=false,AutoSoulReaper=false,AutoTyrant=false,AutoCitizen=false,AutoDragonHunter=false,AutoV2=false,AutoV3=false,AutoTrial=false,AutoMasteryType="Mastery Sword",AutoMastery600=false,Aimbot=false,SelectedPlayer=nil,TeleportPlayer=false,ESPPlayer=false,ESPFruit=false,ESPChest=false,ESPIsland=false,ESPBoss=false,ESPObj={},AntiAFK=true,Noclip=false,AutoStats=false,StatMelee=25,StatSword=25,StatGun=25,StatFruit=25,BoostFPS=false,WalkWater=false,AutoFishing=false,AutoSellFish=false,AutoEquipRod=false,AutoShark=false,AutoPiranha=false,AutoTerrorshark=false,AutoFishCrew=false,AutoSeaBeast=false,ProtectBoat=false,RemoveDamage=false,RemoveNotifications=false,AutoKen=false,AutoHaki=true,WebhookURL="",AutoDropFruit=false,AutoEatFruit=false,SelectedGear="Omega",AutoBuyGear=false,AutoChooseGear=false}
getgenv().FarmDistance=20 getgenv().FarmSpeed=200 getgenv().TweenSpeed=200 getgenv().CustomWalkSpeed=100 getgenv().EnableWalkSpeed=false getgenv().CustomJumpPower=50 getgenv().EnableJumpPower=false getgenv().InfiniteJump=false
local TMS={} local NC={}
task.spawn(function()pcall(function()for _,o in pairs(getnilinstances and getnilinstances()or{})do if o:IsA("Part")and o:GetAttribute("DisplayName")then local d=o:GetAttribute("DisplayName")if string.find(d,"Lv.")then table.insert(TMS,o)end end end end)local wo=WS:FindFirstChild("_WorldOrigin")local es=wo and wo:FindFirstChild("EnemySpawns")if es then for _,o in pairs(es:GetChildren())do if o:IsA("Part")and o:GetAttribute("DisplayName")then local d=o:GetAttribute("DisplayName")if string.find(d,"Lv.")and not table.find(TMS,o)then table.insert(TMS,o)end end end end end)
local function CN(n)if string.find(n,"Lv.")then return(n:gsub(" %pLv. %d+%p",""))end return n end
local function FSP(n,a)local c=CN(n)for _,sp in pairs(TMS)do if sp:IsA("Part")then local sc=CN(sp.Name)if sc==n or sc==c or sp.Name==n then if a or not sp:FindFirstChild("Ignored")then return sp end end end end return nil end
function FindEnemy(names,maxR)local h=HRP()if not h then return nil end local en=WS:FindFirstChild("Enemies")if not en then return nil end local lk={}if type(names)=="table"then for _,n in ipairs(names)do lk[n]=true end else lk[names]=true end local ms=maxR and(maxR*maxR)or math.huge local pos=h.Position local b,bd=nil,ms for _,e in ipairs(en:GetChildren())do local hu=e:FindFirstChild("Humanoid")if hu and hu.Health>0 then local cl=NC[e.Name]or e.Name:match("^(.-)%s*%[")or e.Name NC[e.Name]=cl if lk[cl]or lk[e.Name]then local t=e:FindFirstChild("HumanoidRootPart")if t then local d=(t.Position-pos).Magnitude if d<bd then b,bd=e,d end end end end end return b end
local BS={target=nil,spot=nil,last=0}
function BringMob(t)if not S.BringMob then return end if not t or not t.Parent then return end local r=t:FindFirstChild("HumanoidRootPart")local h=t:FindFirstChildOfClass("Humanoid")if not r or not h or h.Health<=0 then return end if BS.target~=t then BS.target=t local sp=FSP(t.Name,true)BS.spot=sp and sp.CFrame or r.CFrame local en=WS:FindFirstChild("Enemies")if en then for _,m in ipairs(en:GetChildren())do local ig=m:FindFirstChild("Ignored")if ig then ig:Destroy()end end end end local hp=HRP()if not hp then return end if tick()-BS.last<0.1 then return end BS.last=tick()if sethiddenproperty then pcall(function()sethiddenproperty(P,"SimulationRadius",math.huge)sethiddenproperty(P,"MaxSimulationRadius",math.huge)end)end local sp=BS.spot if not sp then return end local en=WS:FindFirstChild("Enemies")if not en then return end local g={}if not t:FindFirstChild("Ignored")then table.insert(g,t)end local mc=S.BringCount or 2 local rad=(mc>2)and 350 or 200 for _,m in ipairs(en:GetChildren())do if m~=t and m.Name==t.Name and not m:FindFirstChild("Ignored")then local mh=m:FindFirstChildOfClass("Humanoid")local mr=m:FindFirstChild("HumanoidRootPart")if mh and mr and mh.Health>0 then local d=(mr.Position-sp.Position).Magnitude if d<=rad and#g<mc then table.insert(g,m)end end end end if P:DistanceFromCharacter(r.Position)<=50 and#g>=2 then for _,m in pairs(g)do local mr=m:FindFirstChild("HumanoidRootPart")local mh=m:FindFirstChildOfClass("Humanoid")if mr and mh then for _,p in ipairs(m:GetDescendants())do if p:IsA("BasePart")and p.CanCollide then p.CanCollide=false end end if mr.Size.X<30 then mr.Size=Vector3.new(50,50,50)mr.CanCollide=false mr.AssemblyLinearVelocity=Vector3.zero mr.AssemblyAngularVelocity=Vector3.zero end mr.CFrame=sp*CFrame.new(math.random(-8,8)/10,-3,math.random(-8,8)/10)mh.WalkSpeed=0 mh.AutoRotate=false mh.BreakJointsOnDeath=false pcall(function()mh:ChangeState(Enum.HumanoidStateType.Physics)end)end end end end
function AutoHaki()if not Alive()then return end if not P.Character:FindFirstChild("HasBuso")then pcall(function()CF:InvokeServer("Buso")end)end end
getgenv().EquipTime=0
function EquipWeapon(n)if tick()-getgenv().EquipTime<0.3 then return end getgenv().EquipTime=tick()if not n then return end local bp=P:FindFirstChild("Backpack")if not bp then return end local t=bp:FindFirstChild(n)if t and t:IsA("Tool")then P.Character.Humanoid:EquipTool(t)return end for _,x in ipairs(bp:GetChildren())do if x:IsA("Tool")and x.ToolTip==n then P.Character.Humanoid:EquipTool(x)return end end end
function AttackNoCD()local c=P.Character if not c then return end local tl=c:FindFirstChildOfClass("Tool")if not tl then return end local en=WS:FindFirstChild("Enemies")if not en then return end local h=HRP()if not h then return end local mp=h.Position local hits,main={},nil for _,e in ipairs(en:GetChildren())do local hu=e:FindFirstChild("Humanoid")local t=e:FindFirstChild("HumanoidRootPart")if hu and t and hu.Health>0 and(t.Position-mp).Magnitude<=60 then local hd=e:FindFirstChild("Head")or t table.insert(hits,{e,hd})main=hd end end if not main then return end if tl:FindFirstChild("LeftClickRemote")then local i=1 for _,x in ipairs(hits)do pcall(function()local r=x[1]:FindFirstChild("HumanoidRootPart")if r then tl.LeftClickRemote:FireServer((r.Position-mp).Unit,i)i=i+1 end end)end elseif Net then local RA=Net:FindFirstChild("RE/RegisterAttack")local RH=Net:FindFirstChild("RE/RegisterHit")if RA and RH then pcall(function()RA:FireServer(0.1)RH:FireServer(main,hits)end)end end end
local FNC=nil
local function SetNoc(on)if on then if FNC then return end FNC=RS2.Stepped:Connect(function()pcall(function()if P.Character then for _,v in pairs(P.Character:GetDescendants())do if v:IsA("BasePart")then v.CanCollide=false end end end end)end)else if FNC then FNC:Disconnect()FNC=nil end end end
local function AnyFarm()return S.AutoFarm or S.AutoFarmNearest or S.AutoChest or S.AutoFarmMaterial or S.AutoFarmBones or S.AutoFarmSea or S.AutoBoss or S.AutoCakePrince or S.AutoDoughKing or S.AutoEliteHunter or S.AutoSoulReaper or S.AutoTyrant or S.AutoCitizen or S.AutoDragonHunter or S.AutoMastery600 end
function FarmTP(goal,spd,ct)if not goal or not Alive()then return end local h=HRP()if not h then return end spd=spd or getgenv().FarmSpeed or 200 local gp=goal.Position local id=(h.Position-gp).Magnitude local to=ct or math.max(15,id/spd*3)SetNoc(true)local lt=tick()local ts=tick()while true do if not AnyFarm()then break end if not Alive()then break end local r=HRP()if not r then break end local d=(r.Position-gp).Magnitude if d<2 then break end if tick()-ts>to then break end local dt=tick()-lt lt=tick()if dt<=0 then dt=0.016 end if dt>0.2 then dt=0.2 end local dir=(gp-r.Position).Unit local mv=math.min(spd*dt,d)r.CFrame=r.CFrame+dir*mv r.AssemblyLinearVelocity=Vector3.zero r.AssemblyAngularVelocity=Vector3.zero RS2.Heartbeat:Wait()end if Alive()then local r=HRP()if r then local fd=(r.Position-gp).Magnitude if fd>0.5 and fd<10 then r.CFrame=CFrame.new(gp,r.Position+r.CFrame.LookVector)end end end SetNoc(false)end
local CC,CCD={},false
local function BCC()if CCD then return end CCD=true CC={}pcall(function()for _,o in ipairs(game:GetDescendants())do if o.Name:find("Chest")and o.ClassName=="Part"then table.insert(CC,o)end end end)end
local function GSC()BCC()local c=P.Character if not c then return{}end local r=c:FindFirstChild("LowerTorso")or c:FindFirstChild("HumanoidRootPart")if not r then return{}end local a={}for _,ch in ipairs(CC)do if ch and ch.Parent and ch:FindFirstChild("TouchInterest")then table.insert(a,ch)end end local rp=r.Position table.sort(a,function(x,y)return(rp-x.Position).Magnitude<(rp-y.Position).Magnitude end)return a end
local function CESP(pt,tx,cl)if not pt or not pt:IsA("BasePart")then return end if S.ESPObj[pt]and S.ESPObj[pt].Parent then local l=S.ESPObj[pt]:FindFirstChild("SX_ESP_Label")if l then l.Text=tx end return end local bb=Instance.new("BillboardGui")bb.Name="SX_ESP_BB"bb.Size=UDim2.new(0,150,0,40)bb.StudsOffset=Vector3.new(0,3,0)bb.AlwaysOnTop=true bb.Parent=pt local l=Instance.new("TextLabel")l.Name="SX_ESP_Label"l.Size=UDim2.fromScale(1,1)l.BackgroundTransparency=1 l.Text=tx l.TextColor3=cl l.TextStrokeTransparency=0 l.TextStrokeColor3=Color3.new(0,0,0)l.TextScaled=true l.Font=Enum.Font.GothamBold l.Parent=bb S.ESPObj[pt]=bb end
local function CESPAll()for p,bb in pairs(S.ESPObj)do pcall(function()bb:Destroy()end)S.ESPObj[p]=nil end end
pcall(function()local o=GP:FindFirstChild("SysxHub")if o then o:Destroy()end end)
pcall(function()local o=GP:FindFirstChild("SysxHubLogo")if o then o:Destroy()end end)
local G=Instance.new("ScreenGui")G.Name="SysxHub"G.ResetOnSpawn=false G.IgnoreGuiInset=true G.DisplayOrder=999999 G.ZIndexBehavior=Enum.ZIndexBehavior.Global G.Parent=GP
local LG=Instance.new("ScreenGui")LG.Name="SysxHubLogo"LG.ResetOnSpawn=false LG.IgnoreGuiInset=true LG.DisplayOrder=999998 LG.ZIndexBehavior=Enum.ZIndexBehavior.Global LG.Parent=GP
local LB=Cr("TextButton",{Parent=LG,Size=UDim2.fromOffset(50,50),Position=UDim2.fromOffset(20,200),BackgroundColor3=T.BM,BorderSizePixel=0,Text="SX",TextColor3=T.AB,TextSize=16,Font=Enum.Font.GothamBold,AutoButtonColor=false,ZIndex=999998})
Cn(LB,25) RA(Sk(LB,BP[1],2,0.1))
do local dg=false ds=nil spp=nil mv=false LB.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=true mv=false ds=i.Position spp=LB.Position i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then dg=false if not mv then G.Enabled=not G.Enabled Notify(G.Enabled and"UI Opened"or"UI Hidden")end end end)end end)UIS.InputChanged:Connect(function(i)if not dg then return end if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then local d=i.Position-ds if math.abs(d.X)>8 or math.abs(d.Y)>8 then mv=true end LB.Position=UDim2.new(spp.X.Scale,spp.X.Offset+d.X,spp.Y.Scale,spp.Y.Offset+d.Y)end end)end
local NF=Cr("TextLabel",{Parent=LG,AnchorPoint=Vector2.new(0.5,1),Position=UDim2.new(0.5,0,1,-20),Size=UDim2.fromOffset(360,44),BackgroundColor3=T.BS,BackgroundTransparency=0.05,Text="",TextColor3=T.AB,TextSize=13,Font=Enum.Font.GothamMedium,Visible=false,ZIndex=999999})
Cn(NF,12) RA(Sk(NF,BP[1],1.5,0.2))
local M=Cr("Frame",{Parent=G,Size=UDim2.fromOffset(700,540),Position=UDim2.new(0.5,-350,0.5,-270),BackgroundColor3=T.BM,BorderSizePixel=0,Visible=true,ClipsDescendants=true,ZIndex=10})
Cn(M,18) RA(Sk(M,BP[1],1.2,0.45))
local HD=Cr("Frame",{Parent=M,Size=UDim2.new(1,0,0,74),BackgroundTransparency=1,ZIndex=20})
Cr("TextLabel",{Parent=HD,BackgroundTransparency=1,Position=UDim2.fromOffset(20,10),Size=UDim2.fromOffset(340,22),Text="SysxHub",TextColor3=T.AB,TextSize=20,Font=Enum.Font.GothamBold,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=22})
Cr("TextLabel",{Parent=HD,BackgroundTransparency=1,Position=UDim2.fromOffset(20,32),Size=UDim2.fromOffset(340,15),Text="Freemium v2.4 - Bring Mob",TextColor3=T.TS2,TextSize=10,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=22})
local CL=Cr("TextButton",{Parent=HD,Size=UDim2.fromOffset(36,36),Position=UDim2.new(1,-52,0,12),BackgroundColor3=T.BS,BackgroundTransparency=0.1,Text="x",TextColor3=T.AB,TextSize=18,Font=Enum.Font.GothamBold,AutoButtonColor=false,ZIndex=25})
Cn(CL,10) RA(Sk(CL,BP[1],1.2,0.35))
Cr("Frame",{Parent=HD,Size=UDim2.new(1,-32,0,1),Position=UDim2.new(0,16,1,-2),BackgroundColor3=Color3.fromRGB(60,90,150),BackgroundTransparency=0.6,BorderSizePixel=0,ZIndex=22})
local CT=Cr("Frame",{Parent=M,Size=UDim2.new(1,-32,1,-90),Position=UDim2.fromOffset(16,80),BackgroundTransparency=1,ZIndex=14})
local SB=Cr("Frame",{Parent=CT,BackgroundColor3=T.BS,Size=UDim2.new(0,145,1,0),BorderSizePixel=0,ZIndex=15})
Cn(SB,12) Sk(SB,T.BD,1,0.5)
local TL=Cr("ScrollingFrame",{Parent=SB,BackgroundTransparency=1,Position=UDim2.new(0,6,0,6),Size=UDim2.new(1,-12,1,-12),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=2,ScrollBarImageColor3=Color3.fromRGB(80,130,220),BorderSizePixel=0,ZIndex=16})
local L1=Instance.new("UIListLayout")L1.Padding=UDim.new(0,4)L1.SortOrder=Enum.SortOrder.LayoutOrder L1.Parent=TL
local CS2=Cr("ScrollingFrame",{Parent=CT,BackgroundTransparency=1,Position=UDim2.new(0,155,0,0),Size=UDim2.new(1,-155,1,0),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=3,ScrollBarImageColor3=Color3.fromRGB(80,130,220),BorderSizePixel=0,ZIndex=14})
local PG2,TB2={},{}
local function CPage(n)local x=Cr("ScrollingFrame",{Name=n,Parent=CS2,BackgroundTransparency=1,Position=UDim2.new(0,4,0,4),Size=UDim2.new(1,-8,1,-8),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=3,ScrollBarImageColor3=Color3.fromRGB(80,130,220),BorderSizePixel=0,Visible=false,ZIndex=12})local l=Instance.new("UIListLayout")l.Padding=UDim.new(0,6)l.SortOrder=Enum.SortOrder.LayoutOrder l.Parent=x PG2[n]=x return x end
local function CTab(n,o)local b=Cr("TextButton",{Parent=TL,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,30),Text="",AutoButtonColor=false,BorderSizePixel=0,LayoutOrder=o,ZIndex=17})Cn(b,8)local l=Cr("TextLabel",{Parent=b,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(1,-14,1,0),Text=n,TextColor3=T.TS2,TextSize=10,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=18})TB2[n]={B=b,L=l,S=nil}b.MouseEnter:Connect(function()if TB2[n].L.TextColor3~=T.AB then TW(b,{BackgroundColor3=T.BH},0.15)end end)b.MouseLeave:Connect(function()if TB2[n].L.TextColor3~=T.AB then TW(b,{BackgroundColor3=T.BS},0.15)end end)return b end
local function STab(n)for pn,pg in pairs(PG2)do pg.Visible=(pn==n)end for tn,d in pairs(TB2)do if tn==n then d.B.BackgroundColor3=T.BA d.L.TextColor3=T.AB if d.S then d.S:Destroy()end d.S=Sk(d.B,BP[1],1.2,0.15)RA(d.S)else d.B.BackgroundColor3=T.BS d.L.TextColor3=T.TS2 if d.S then d.S:Destroy()d.S=nil end end end end
local function CTg(pr,tx,df,cb)local st=df and true or false local b=Cr("TextButton",{Parent=pr,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,38),Text="",AutoButtonColor=false,BorderSizePixel=0,ZIndex=100})Cn(b,9)RA(Sk(b,BP[1],1,0.55))Cr("TextLabel",{Parent=b,BackgroundTransparency=1,Position=UDim2.new(0,12,0,0),Size=UDim2.new(1,-58,1,0),Text=tx,TextColor3=T.TP,TextSize=11,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=101})local i=Cr("Frame",{Parent=b,BackgroundColor3=T.TF,Size=UDim2.fromOffset(36,20),Position=UDim2.new(1,-48,0.5,-10),ZIndex=101})Cn(i,20)local d=Cr("Frame",{Parent=i,BackgroundColor3=T.TDF,Size=UDim2.fromOffset(14,14),Position=UDim2.new(0,3,0.5,-7),ZIndex=102})Cn(d,20)local function rr()if st then i.BackgroundColor3=T.TO d.BackgroundColor3=T.TDO d.Position=UDim2.new(1,-17,0.5,-7)else i.BackgroundColor3=T.TF d.BackgroundColor3=T.TDF d.Position=UDim2.new(0,3,0.5,-7)end end b.Activated:Connect(function()st=not st rr()if cb then pcall(cb,st)end end)rr()return b end
local function CBt(pr,tx,cb)local b=Cr("TextButton",{Parent=pr,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,38),Text=tx,TextColor3=T.TP,TextSize=11,Font=Enum.Font.GothamMedium,AutoButtonColor=false,BorderSizePixel=0,ZIndex=100})Cn(b,9)RA(Sk(b,BP[1],1.1,0.55))b.MouseEnter:Connect(function()TW(b,{BackgroundColor3=T.BH},0.15)end)b.MouseLeave:Connect(function()TW(b,{BackgroundColor3=T.BS},0.15)end)b.Activated:Connect(function()TW(b,{BackgroundColor3=T.BA},0.08)task.delay(0.1,function()TW(b,{BackgroundColor3=T.BS},0.15)end)if cb then pcall(cb)end end)return b end
local function CDd(pr,ti,op,cb)op=op or{"-"}local H=Cr("Frame",{Parent=pr,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,38),BorderSizePixel=0,ZIndex=100})Cn(H,9)RA(Sk(H,BP[1],1.1,0.55))local Sl=op[1]or"-"local Lb=Cr("TextLabel",{Parent=H,BackgroundTransparency=1,Position=UDim2.new(0,12,0,0),Size=UDim2.new(1,-32,1,0),Text=ti..": "..Sl,TextColor3=T.TP,TextSize=11,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=101})Cr("TextLabel",{Parent=H,BackgroundTransparency=1,Position=UDim2.new(1,-22,0,0),Size=UDim2.new(0,16,1,0),Text="v",TextColor3=T.SBS,TextSize=11,Font=Enum.Font.GothamBold,ZIndex=101})local ck=Cr("TextButton",{Parent=H,BackgroundTransparency=1,Size=UDim2.new(1,0,1,0),Text="",AutoButtonColor=false,ZIndex=110})ck.Activated:Connect(function()local Pp=Cr("Frame",{Parent=G,AnchorPoint=Vector2.new(0.5,0.5),Position=UDim2.new(0.5,0,0.5,0),Size=UDim2.fromOffset(300,math.min(#op*38+80,420)),BackgroundColor3=T.BS,BorderSizePixel=0,ZIndex=999990})Cn(Pp,14)RA(Sk(Pp,BP[1],1.5,0.25))Cr("TextLabel",{Parent=Pp,BackgroundTransparency=1,Position=UDim2.fromOffset(18,10),Size=UDim2.new(1,-60,0,22),Text=ti,TextColor3=T.AB,TextSize=14,Font=Enum.Font.GothamBold,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=999991})local xb=Cr("TextButton",{Parent=Pp,Position=UDim2.new(1,-40,0,10),Size=UDim2.fromOffset(28,22),Text="x",TextColor3=T.TM,TextSize=14,BackgroundTransparency=1,Font=Enum.Font.GothamBold,AutoButtonColor=false,ZIndex=999992})xb.Activated:Connect(function()Pp:Destroy()end)local LS=Cr("ScrollingFrame",{Parent=Pp,BackgroundTransparency=1,Position=UDim2.fromOffset(12,42),Size=UDim2.new(1,-24,1,-54),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=3,ScrollBarImageColor3=Color3.fromRGB(80,130,220),BorderSizePixel=0,ZIndex=999991})local LL=Instance.new("UIListLayout")LL.Padding=UDim.new(0,4)LL.SortOrder=Enum.SortOrder.LayoutOrder LL.Parent=LS for i,o in ipairs(op)do local ob=Cr("TextButton",{Parent=LS,BackgroundColor3=T.BT,Size=UDim2.new(1,-8,0,34),Position=UDim2.new(0,4,0,0),Text=o,TextColor3=T.TP,TextSize=12,Font=Enum.Font.GothamMedium,AutoButtonColor=false,BorderSizePixel=0,LayoutOrder=i,ZIndex=999992,TextXAlignment=Enum.TextXAlignment.Left})Cn(ob,7)local pd=Instance.new("UIPadding")pd.PaddingLeft=UDim.new(0,12)pd.Parent=ob ob.MouseEnter:Connect(function()TW(ob,{BackgroundColor3=T.BH},0.1)end)ob.MouseLeave:Connect(function()TW(ob,{BackgroundColor3=T.BT},0.1)end)ob.Activated:Connect(function()Sl=o Lb.Text=ti..": "..o if cb then pcall(cb,o)end Pp:Destroy()end)end end)return H end
local function CSl(pr,ti,mnv,mxv,df,cb)local vl=df or mnv local H=Cr("Frame",{Parent=pr,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,58),BorderSizePixel=0,ZIndex=100})Cn(H,9)RA(Sk(H,BP[1],1,0.55))Cr("TextLabel",{Parent=H,BackgroundTransparency=1,Position=UDim2.new(0,14,0,8),Size=UDim2.new(1,-90,0,16),Text=ti,TextColor3=T.TS2,TextSize=10,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,ZIndex=101})local VH=Cr("Frame",{Parent=H,BackgroundColor3=T.BT,Position=UDim2.new(1,-74,0,6),Size=UDim2.fromOffset(60,20),ZIndex=101})Cn(VH,6)Sk(VH,T.BD,1,0.4)local VL=Cr("TextLabel",{Parent=VH,BackgroundTransparency=1,Size=UDim2.fromScale(1,1),Text=tostring(vl),TextColor3=T.SBS,TextSize=11,Font=Enum.Font.GothamBold,ZIndex=102})local TB=Cr("Frame",{Parent=H,BackgroundColor3=T.BT,Position=UDim2.new(0,14,0,36),Size=UDim2.new(1,-28,0,6),BorderSizePixel=0,ZIndex=101})Cn(TB,4)local fr=(vl-mnv)/(mxv-mnv)local FL=Cr("Frame",{Parent=TB,BackgroundColor3=T.SB,Size=UDim2.new(fr,0,1,0),BorderSizePixel=0,ZIndex=102})Cn(FL,4)local KN=Cr("Frame",{Parent=TB,BackgroundColor3=Color3.new(1,1,1),Size=UDim2.fromOffset(14,14),Position=UDim2.new(fr,-7,0.5,-7),BorderSizePixel=0,ZIndex=103})Cn(KN,20)Sk(KN,T.BM,1.5,0)local BT=Cr("TextButton",{Parent=H,BackgroundTransparency=1,Size=UDim2.new(1,0,0,34),Position=UDim2.new(0,0,0,22),Text="",AutoButtonColor=false,ZIndex=110})local dg=false local function upd(mx)local ab=TB.AbsolutePosition local sz=TB.AbsoluteSize if sz.X==0 then return end local r=math.clamp((mx-ab.X)/sz.X,0,1)vl=math.floor(mnv+(mxv-mnv)*r+0.5)FL.Size=UDim2.new(r,0,1,0)KN.Position=UDim2.new(r,-7,0.5,-7)VL.Text=tostring(vl)if cb then pcall(cb,vl)end end BT.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=true upd(i.Position.X)end end)UIS.InputChanged:Connect(function(i)if dg and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then upd(i.Position.X)end end)UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=false end end)return H end
local function CLb(pr,tx,sz)local l=Cr("TextLabel",{Parent=pr,BackgroundColor3=T.BS,Size=UDim2.new(1,0,0,sz or 28),Text=tx,TextColor3=T.TP,TextSize=10,Font=Enum.Font.GothamMedium,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,BorderSizePixel=0,ZIndex=100})Cn(l,9)RA(Sk(l,BP[1],1,0.55))local pd=Instance.new("UIPadding")pd.PaddingLeft=UDim.new(0,12)pd.PaddingTop=UDim.new(0,6)pd.Parent=l return l end
function Notify(tx)if not NF or not NF.Parent then return end NF.__tk=(NF.__tk or 0)+1 local tk=NF.__tk NF.Text=tostring(tx)NF.Visible=true NF.TextTransparency=1 NF.BackgroundTransparency=1 TW(NF,{TextTransparency=0,BackgroundTransparency=0.05},0.25)task.delay(2.5,function()if tk~=NF.__tk then return end TW(NF,{TextTransparency=1,BackgroundTransparency=1},0.25)task.wait(0.25)if tk==NF.__tk then NF.Visible=false end end)end
local function TryBuy(c,...)local a={...}local ok=pcall(function()return CF:InvokeServer(c,table.unpack(a))end)Notify(ok and"Purchased: "..c or"Failed: "..c)end
local cidx=1
task.spawn(function()while task.wait(3)do cidx=(cidx%#BP)+1 local tc=BP[cidx]for _,s in ipairs(AR)do if s and s.Parent then pcall(function()TS:Create(s,TweenInfo.new(2.6,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut),{Color=tc}):Play()end)end end end end)
local TD={{"Home"},{"Farm"},{"PvP"},{"Sea"},{"Fishing"},{"Stats"},{"Race"},{"Fruit & Raid"},{"Quest & Item"},{"Visual"},{"Teleport"},{"Shop"},{"Settings"},{"Misc"}}
for i,d in ipairs(TD)do local b=CTab(d[1],i)b.Activated:Connect(function()STab(d[1])end)end
local HP=CPage("Home")local FP=CPage("Farm")local PP=CPage("PvP")local SP=CPage("Sea")local FiP=CPage("Fishing")local StP=CPage("Stats")local RP=CPage("Race")local FRP=CPage("Fruit & Raid")local QIP=CPage("Quest & Item")local VP=CPage("Visual")local TPg=CPage("Teleport")local ShP=CPage("Shop")local SeP=CPage("Settings")local MP=CPage("Misc")
CLb(HP,"=== SysxHub v2.4 ===",32)
local HI=CLb(HP,"Bring Mob System + Logo\n\nTap 'SX' logo untuk hide/show UI\nDrag logo untuk pindah posisi",180)HI.TextSize=11 HI.TextYAlignment=Enum.TextYAlignment.Top
CBt(HP,"Join Discord Server",function()if setclipboard then setclipboard(DC)end pcall(function()GS:OpenBrowserWindow(DC)end)Notify("Opening Discord...")end)
CLb(HP,"SysxHub | Freemium v2.4",34)
CLb(FP,"=== Farm Settings ===",26)
CDd(FP,"Select Weapon",{"Melee","Sword","Blox Fruit","Gun"},function(o)S.SelectedWeapon=o end)
CLb(FP,"=== Auto Farm ===",26)
CTg(FP,"Auto Farm Level",false,function(s)S.AutoFarm=s Notify(s and"Auto Farm Level ON"or"Auto Farm Level OFF")end)
CTg(FP,"Auto Farm Nearest",false,function(s)S.AutoFarmNearest=s end)
CTg(FP,"Auto Collect Chest",false,function(s)S.AutoChest=s if s then CCD=false CC={}end end)
CTg(FP,"Auto Farm Bones",false,function(s)S.AutoFarmBones=s end)
CLb(FP,"=== Material Farm ===",26)
local ML=W1 and{"Angel Wings","Leather + Scrap Metal","Magma Ore","Fish Tail"}or W2 and{"Leather + Scrap Metal","Magma Ore","Mystic Droplet","Radioactive Material","Vampire Fang"}or W3 and{"Leather + Scrap Metal","Fish Tail","Gunpowder","Mini Tusk","Conjured Cocoa","Dragon Scale"}or{"None"}
CDd(FP,"Select Material",ML,function(o)S.SelectedMaterial=o end)
CTg(FP,"Auto Farm Material",false,function(s)S.AutoFarmMaterial=s end)
CLb(FP,"=== BOSS FARM ===",26)
local BL={"Greybeard","The Saw","Saber Expert","The Gorilla King","Bobby","Yeti","Vice Admiral","Warden","Chief Warden","Swan","Magma Admiral","Fishman Lord","Wysper","Thunder God","Cyborg","Darkbeard","Cursed Captain","Order","Don Swan","Diamond","Jeremy","Fajita","Smoke Admiral","Awakened Ice Admiral","Tide Keeper","Dough King","Cake Prince","rip_indra True Form","Soul Reaper","Stone","Island Empress","Kilo Admiral","Captain Elephant","Beautiful Pirate","Cake Queen","Longma"}
CDd(FP,"Select Boss",BL,function(o)S.SelectedBoss=o end)
local BSt=CLb(FP,"Boss Status: -",28)BSt.TextSize=11
CTg(FP,"Kill Select Boss",false,function(s)S.AutoBoss=s end)
CLb(PP,"=== PvP ===",26)
local PL={"None"}for _,p in ipairs(Players:GetPlayers())do if p~=P then table.insert(PL,p.Name)end end
CDd(PP,"Select Player",PL,function(o)S.SelectedPlayer=o end)
CTg(PP,"Teleport To Player",false,function(s)S.TeleportPlayer=s end)
CTg(PP,"Auto Aimbot",false,function(s)S.Aimbot=s end)
CLb(SP,"=== Sea Settings ===",26)
CDd(SP,"Select Boat",{"PirateBrigade","PirateGrandBrigade","MarineBrigade","MarineGrandBrigade","Beast Hunter"},function(o)getgenv().SelectedBoat=o end)
CTg(SP,"Auto Farm Sea",false,function(s)S.AutoFarmSea=s end)
CTg(SP,"Protect Boat",false,function(s)S.ProtectBoat=s end)
CLb(SP,"=== Sea Enemies ===",26)
CTg(SP,"Auto Shark",false,function(s)S.AutoShark=s end)
CTg(SP,"Auto Piranha",false,function(s)S.AutoPiranha=s end)
CTg(SP,"Auto Terrorshark",false,function(s)S.AutoTerrorshark=s end)
CTg(SP,"Auto Fish Crew",false,function(s)S.AutoFishCrew=s end)
CTg(SP,"Auto Sea Beast",false,function(s)S.AutoSeaBeast=s end)
CLb(SP,"=== Find Islands ===",26)
CTg(SP,"Find Mirage Island",false,function(s)getgenv().FindMirage=s end)
CTg(SP,"Find Prehistoric Island",false,function(s)getgenv().FindPrehistoric=s end)
CTg(SP,"Find Frozen Dimension",false,function(s)getgenv().FindFrozen=s end)
CTg(SP,"Find Kitsune Island",false,function(s)getgenv().FindKitsune=s end)
CLb(FiP,"=== Fishing ===",26)
CTg(FiP,"Auto Equip Rod",false,function(s)S.AutoEquipRod=s end)
CTg(FiP,"Auto Fishing",false,function(s)S.AutoFishing=s end)
CTg(FiP,"Auto Sell Fish",false,function(s)S.AutoSellFish=s end)
CLb(StP,"=== Auto Add Stat ===",26)
CTg(StP,"Auto Add Stat",false,function(s)S.AutoStats=s Notify(s and"Auto Add Stat ON"or"Auto Add Stat OFF")end)
CLb(StP,"=== Stat Distribution ===",26)
CSl(StP,"Melee",1,100,25,function(v)S.StatMelee=v end)
CSl(StP,"Sword",1,100,25,function(v)S.StatSword=v end)
CSl(StP,"Gun",1,100,25,function(v)S.StatGun=v end)
CSl(StP,"Fruit",1,100,25,function(v)S.StatFruit=v end)
CLb(RP,"=== Race V4 ===",26)
CTg(RP,"No Frog",false,function(s)if s then LT.FogEnd=100000 for _,d in pairs(LT:GetDescendants())do if d:IsA("Atmosphere")then d:Destroy()end end end end)
CBt(RP,"Teleport Temple of Time",function()local h=HRP()if h then h.CFrame=CFrame.new(28286.35,14895.30,102.62)end local ms=RS:FindFirstChild("MapStash")local tot=ms and ms:FindFirstChild("Temple of Time")if tot then tot.Parent=WS.Map end Notify("At Temple of Time")end)
CTg(RP,"Auto Buy Gear V4",false,function(s)S.AutoBuyGear=s end)
CDd(RP,"Select Gear V4",{"Alpha","Omega"},function(o)S.SelectedGear=o end)
CTg(RP,"Auto Choose Gears",false,function(s)S.AutoChooseGear=s end)
CTg(RP,"Auto Trial",false,function(s)S.AutoTrial=s end)
CLb(RP,"=== Race V2-V3 ===",26)
CTg(RP,"Auto V2",false,function(s)S.AutoV2=s end)
CTg(RP,"Auto V3",false,function(s)S.AutoV3=s end)
CLb(FRP,"=== Fruit ===",26)
CTg(FRP,"Auto Store Fruit",false,function(s)S.AutoStoreFruit=s end)
CTg(FRP,"Auto Buy Random Fruit",false,function(s)S.AutoBuyFruit=s end)
CTg(FRP,"Tween to Fruit",false,function(s)S.AutoFindFruit=s end)
CTg(FRP,"Auto Drop Fruit",false,function(s)S.AutoDropFruit=s end)
CTg(FRP,"Auto Eat Fruit",false,function(s)S.AutoEatFruit=s end)
CLb(FRP,"=== Raid ===",26)
CDd(FRP,"Select Chip",{"Flame","Ice","Sand","Dark","Light","Magma","Quake","Buddha","Love","Spider","Sound","Phoenix","Portal","Rumble","Pain","Blizzard","Gravity"},function(o)getgenv().SelectedChip=o end)
CTg(FRP,"Auto Raid",false,function(s)S.AutoRaid=s end)
CTg(FRP,"Auto Awaken Fruit",false,function(s)S.AutoAwaken=s end)
CLb(QIP,"=== Special Boss ===",26)
CTg(QIP,"Auto Cake Prince",false,function(s)S.AutoCakePrince=s end)
CTg(QIP,"Auto Dough King",false,function(s)S.AutoDoughKing=s end)
CTg(QIP,"Auto Elite Hunter",false,function(s)S.AutoEliteHunter=s end)
CTg(QIP,"Auto Soul Reaper",false,function(s)S.AutoSoulReaper=s end)
CTg(QIP,"Auto Kill Tyrant",false,function(s)S.AutoTyrant=s end)
CTg(QIP,"Auto Citizen Quest",false,function(s)S.AutoCitizen=s end)
CTg(QIP,"Auto Dragon Hunter",false,function(s)S.AutoDragonHunter=s end)
CLb(QIP,"=== Mastery 600 ===",26)
CDd(QIP,"Mastery Type",{"Mastery Sword","Mastery Gun","Mastery Fruit"},function(o)S.AutoMasteryType=o end)
CTg(QIP,"Auto 600 Mastery",false,function(s)S.AutoMastery600=s end)
CLb(VP,"=== ESP ===",26)
CTg(VP,"ESP Player",false,function(s)S.ESPPlayer=s if not s then CESPAll()end end)
CTg(VP,"ESP Fruit",false,function(s)S.ESPFruit=s if not s then CESPAll()end end)
CTg(VP,"ESP Chest",false,function(s)S.ESPChest=s if not s then CESPAll()end end)
CTg(VP,"ESP Boss",false,function(s)S.ESPBoss=s if not s then CESPAll()end end)
CLb(TPg,"=== Sea Travel ===",26)
CBt(TPg,"Travel to Sea 1",function()CF:InvokeServer("TravelMain")Notify("Traveling Sea 1")end)
CBt(TPg,"Travel to Sea 2",function()CF:InvokeServer("TravelDressrosa")Notify("Traveling Sea 2")end)
CBt(TPg,"Travel to Sea 3",function()CF:InvokeServer("TravelZou")Notify("Traveling Sea 3")end)
CLb(ShP,"=== Buy Fighting Style (All) ===",26)
CBt(ShP,"Buy All Fighting Styles",function()local l={"BuyBlackLeg","BuyElectro","BuyFishmanKarate","BuySuperhuman","BuyDeathStep","BuySharkmanKarate","BuyElectricClaw","BuyDragonTalon","BuyGodhuman","BuySanguineArt"}for _,c in ipairs(l)do pcall(function()CF:InvokeServer(c)end)task.wait(0.5)end Notify("All Fighting Styles purchased")end)
CLb(ShP,"=== Buy Abilities (All) ===",26)
CBt(ShP,"Buy All Abilities",function()pcall(function()CF:InvokeServer("BuyHaki","Geppo")end)task.wait(0.3)pcall(function()CF:InvokeServer("BuyHaki","Buso")end)task.wait(0.3)pcall(function()CF:InvokeServer("KenTalk","Buy")end)task.wait(0.3)pcall(function()CF:InvokeServer("BuyHaki","Soru")end)Notify("All Abilities purchased")end)
CLb(ShP,"=== Buy Misc Shop ===",26)
CBt(ShP,"Buy Stat Refund",function()TryBuy("BlackbeardReward","Refund","1")task.wait(0.3)TryBuy("BlackbeardReward","Refund","2")end)
CBt(ShP,"Buy Race Reroll",function()TryBuy("BlackbeardReward","Reroll","1")task.wait(0.3)TryBuy("BlackbeardReward","Reroll","2")end)
CBt(ShP,"Buy Race Ghoul",function()TryBuy("Ectoplasm","BuyCheck",4)task.wait(0.3)TryBuy("Ectoplasm","Change",4)end)
CBt(ShP,"Buy Race Cyborg",function()TryBuy("CyborgTrainer","Buy")end)
CBt(ShP,"Buy Legendary Swords",function()TryBuy("LegendarySwordDealer","1")task.wait(0.3)TryBuy("LegendarySwordDealer","2")task.wait(0.3)TryBuy("LegendarySwordDealer","3")end)
CLb(SeP,"=== Local ===",26)
CTg(SeP,"Anti AFK",true,function(s)S.AntiAFK=s end)
CTg(SeP,"No Clip",false,function(s)S.Noclip=s end)
CTg(SeP,"Auto Ken",false,function(s)S.AutoKen=s end)
CTg(SeP,"Auto Haki",true,function(s)S.AutoHaki=s end)
CLb(SeP,"=== Remove ===",26)
CTg(SeP,"Remove Damage Numbers",false,function(s)S.RemoveDamage=s end)
CTg(SeP,"Remove Notifications",false,function(s)S.RemoveNotifications=s end)
CLb(MP,"=== BRING MOB SYSTEM ===",26)
CTg(MP,"Bring Mob",true,function(s)S.BringMob=s Notify(s and"Bring Mob ON"or"Bring Mob OFF")end)
CSl(MP,"Bring Mob Range",50,1000,300,function(v)S.BringRange=v end)
CSl(MP,"Bring Mob Count",1,10,2,function(v)S.BringCount=v end)
CLb(MP,"=== FARM SETTINGS ===",26)
CSl(MP,"Farm Distance",5,50,20,function(v)getgenv().FarmDistance=v end)
CSl(MP,"Farm Speed",50,500,200,function(v)getgenv().FarmSpeed=v end)
CLb(MP,"=== Combat ===",26)
CTg(MP,"Fast Attack",true,function(s)S.FastAttack=s end)
CSl(MP,"Tween Speed",50,500,200,function(v)getgenv().TweenSpeed=v end)
CTg(MP,"Change WalkSpeed",false,function(s)getgenv().EnableWalkSpeed=s end)
CSl(MP,"WalkSpeed Value",16,300,100,function(v)getgenv().CustomWalkSpeed=v if getgenv().EnableWalkSpeed then local h=P.Character and P.Character:FindFirstChildOfClass("Humanoid")if h then h.WalkSpeed=v end end end)
CTg(MP,"Change JumpPower",false,function(s)getgenv().EnableJumpPower=s end)
CSl(MP,"JumpPower Value",50,500,100,function(v)getgenv().CustomJumpPower=v if getgenv().EnableJumpPower then local h=P.Character and P.Character:FindFirstChildOfClass("Humanoid")if h then h.JumpPower=v end end end)
CTg(MP,"Infinite Jump",false,function(s)getgenv().InfiniteJump=s end)
CTg(MP,"Walk On Water",false,function(s)S.WalkWater=s local w=WS:FindFirstChild("Map")and WS.Map:FindFirstChild("WaterBase-Plane")if w then w.Size=s and Vector3.new(1000,113,1000)or Vector3.new(1000,80,1000)end end)
CLb(MP,"=== Performance ===",26)
CTg(MP,"Boost FPS",false,function(s)S.BoostFPS=s if s then pcall(function()LT.GlobalShadows=false LT.Brightness=0 LT.FogEnd=1e10 LT.Outlines=false end)else pcall(function()LT.GlobalShadows=true LT.Brightness=2 LT.FogEnd=100000 LT.Outlines=true end)end end)
CSl(MP,"FPS Cap",15,240,60,function(v)pcall(function()if setfpscap then setfpscap(v)end end)end)
CTg(MP,"White Screen",false,function(s)pcall(function()RS2:Set3dRenderingEnabled(not s)end)end)
CTg(MP,"Black Screen",false,function(s)local bs=GP:FindFirstChild("SX_BlackScreen")if s then if not bs then bs=Instance.new("ScreenGui")bs.Name="SX_BlackScreen"bs.Parent=GP bs.IgnoreGuiInset=true bs.DisplayOrder=999997 local f=Instance.new("Frame")f.Size=UDim2.fromScale(1,1)f.BackgroundColor3=Color3.new(0,0,0)f.BorderSizePixel=0 f.Parent=bs end elseif bs then bs:Destroy()end end)
CLb(MP,"=== Server ===",26)
CBt(MP,"Rejoin Server",function()TPS:Teleport(game.PlaceId,P)end)
CBt(MP,"Server Hop",function()Notify("Hopping...")pcall(function()local d=HS:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))for _,v in pairs(d.data)do if v.id~=game.JobId and v.playing<v.maxPlayers then pcall(function()TPS:TeleportToPlaceInstance(game.PlaceId,v.id,P)end)return end end end)end)
CLb(MP,"=== Team ===",26)
CBt(MP,"Join Pirates",function()CF:InvokeServer("SetTeam","Pirates")Notify("Joined Pirates")end)
CBt(MP,"Join Marines",function()CF:InvokeServer("SetTeam","Marines")Notify("Joined Marines")end)
CLb(MP,"=== Codes ===",26)
CBt(MP,"Redeem All Codes",function()local c={"KITT_RESET","SUB2GAMEROBOT_RESET1","SUB2GAMERROBOT_EXP1","SUB2OFFICIALNOOBIE","AXIORE","BLUXXY","JCWK","KITTGAMING","MAGICBUS","STARCODEHEO","STRAWHATMAINE","TANTAIGAMING","THEGREATACE","ENYU_IS_PRO","FUDD10","FUDD10_V2","BIGNEWS","CHANDLER","SECRET_ADMIN","ADMIN_MELEE"}for _,x in ipairs(c)do pcall(function()Rem.Redeem:InvokeServer(x)end)task.wait(0.5)end Notify("All codes redeemed")end)
-- LOOPS
task.spawn(function()while task.wait(0.05)do if S.FastAttack and Alive()then pcall(AttackNoCD)end end end)
task.spawn(function()while task.wait(0.5)do pcall(function()if S.AutoHaki then AutoHaki()end end)end end)
task.spawn(function()while task.wait(0.4)do if S.AutoFarm then pcall(function()local h=HRP()if not h then return end local c=P.Character local hu=c and c:FindFirstChildOfClass("Humanoid")if not hu or hu.Health<=0 then return end local qm=nil local qf=PG:FindFirstChild("TrackedQuestFrame")if qf then local inner=qf:FindFirstChild("Frame")if inner and inner.Visible then local lb=inner:FindFirstChild("QuestTitle")or inner:FindFirstChild("Title")or inner:FindFirstChild("TaskTitle")if lb and lb.Text then qm=lb.Text:match("Defeat%s+%d+%s+([%w%s]+)")or lb.Text:match("Defeat%s+([^%[]+)")or lb.Text:match("^([^%[]+)%s*%[")or lb.Text:match("^([^%[]+)")if qm then qm=qm:gsub("%s+$",""):gsub("%(.*%)",""):gsub("%s+$",""):gsub("s$","")end end end end if not qm then local lv=P.Data.Level.Value local Q=require(RS.Quests)for qn,qq in pairs(Q)do for id,q in pairs(qq)do if q.LevelReq==lv then CF:InvokeServer("StartQuest",qn,id)return end end end return end local en=FindEnemy({qm},99999)if en then local t=en:FindFirstChild("HumanoidRootPart")if t then AutoHaki()EquipWeapon(S.SelectedWeapon)local d=(t.Position-h.Position).Magnitude if d>25 then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)else if S.BringMob then BringMob(en)end t.CanCollide=false if t.Size.X<30 then t.Size=Vector3.new(60,60,60)end if en:FindFirstChild("Humanoid")then en.Humanoid.WalkSpeed=0 end AttackNoCD()end end else local sp=FSP(qm,true)if sp then FarmTP(sp.CFrame*CFrame.new(0,60,0),getgenv().FarmSpeed,25)end end end)end end end)
task.spawn(function()while task.wait(0.35)do if S.AutoFarmNearest then pcall(function()local h=HRP()if not h then return end local en=WS:FindFirstChild("Enemies")if not en then return end local b,bd=nil,math.huge for _,e in ipairs(en:GetChildren())do local hu=e:FindFirstChild("Humanoid")local t=e:FindFirstChild("HumanoidRootPart")if hu and t and hu.Health>0 then local d=(t.Position-h.Position).Magnitude if d<bd and d<2000 then b,bd=e,d end end end if b then local t=b:FindFirstChild("HumanoidRootPart")if t then AutoHaki()EquipWeapon(S.SelectedWeapon)local d=(t.Position-h.Position).Magnitude if d>25 then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)end if S.BringMob then BringMob(b)end t.CanCollide=false if t.Size.X<30 then t.Size=Vector3.new(60,60,60)end if b:FindFirstChild("Humanoid")then b.Humanoid.WalkSpeed=0 end AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoChest then pcall(function()local h=HRP()if not h then return end local ch=GSC()if#ch>0 then local t=ch[1]FarmTP(t.CFrame+Vector3.new(0,2,0),getgenv().FarmSpeed,20)pcall(function()firetouchinterest(h,t,0)task.wait(0.05)firetouchinterest(h,t,1)end)end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoFarmBones then pcall(function()local e=FindEnemy({"Reborn Skeleton","Living Zombie","Demonic Soul","Posessed Mummy"},5000)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false if e:FindFirstChild("Humanoid")then e.Humanoid.WalkSpeed=0 end AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoFarmMaterial and S.SelectedMaterial then pcall(function()local mm={["Angel Wings"]={NPCs={"Royal Soldier","Royal Squad"},Pos=CFrame.new(-7742,5634,-1564)},["Leather + Scrap Metal"]={NPCs={"Pirate","Brute","Scrap Metal"},Pos=CFrame.new(-1257,54,4091)},["Magma Ore"]={NPCs={"Military Soldier","Lava Pirate"},Pos=CFrame.new(-5408,11,8456)},["Fish Tail"]={NPCs={"Fishman Warrior","Fishman Captain"},Pos=CFrame.new(60931,19,1574)},["Mystic Droplet"]={NPCs={"Water Fighter"},Pos=CFrame.new(-3350,282,-10527)},["Radioactive Material"]={NPCs={"Factory Staff"},Pos=CFrame.new(-73,149,-112)},["Vampire Fang"]={NPCs={"Vampire"},Pos=CFrame.new(-6030,6,-1281)},["Gunpowder"]={NPCs={"Pistol Billionaire"},Pos=CFrame.new(-394,135,5981)},["Mini Tusk"]={NPCs={"Mythological Pirate"},Pos=CFrame.new(-13510,584,-6986)},["Conjured Cocoa"]={NPCs={"Cocoa Warrior","Chocolate Bar Battler"},Pos=CFrame.new(400,81,-12257)},["Dragon Scale"]={NPCs={"Dragon Crew Archer"},Pos=CFrame.new(6689,378,331)}}local d=mm[S.SelectedMaterial]if not d then return end local e=FindEnemy(d.NPCs,5000)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false if e:FindFirstChild("Humanoid")then e.Humanoid.WalkSpeed=0 end AttackNoCD()end else FarmTP(d.Pos+Vector3.new(0,30,0),getgenv().FarmSpeed,30)end end)end end end)
task.spawn(function()while task.wait(0.4)do if S.AutoBoss and S.SelectedBoss then pcall(function()local e=FindEnemy({S.SelectedBoss},99999)local rb=RS:FindFirstChild(S.SelectedBoss)local sp=e~=nil or(rb and rb:FindFirstChild("HumanoidRootPart")~=nil)if BSt and BSt.Parent then BSt.Text="Boss Status: "..(sp and"Spawned"or"Not Spawned")end if e then local t=e:FindFirstChild("HumanoidRootPart")if t then AutoHaki()EquipWeapon(S.SelectedWeapon)FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false if t.Size.X<40 then t.Size=Vector3.new(80,80,80)end if e:FindFirstChild("Humanoid")then e.Humanoid.WalkSpeed=0 end AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoMastery600 then pcall(function()local mt=S.AutoMasteryType local wp="Melee"if mt=="Mastery Sword"then wp="Sword"elseif mt=="Mastery Gun"then wp="Gun"elseif mt=="Mastery Fruit"then wp="Blox Fruit"end local e=FindEnemy({"Reborn Skeleton","Living Zombie","Demonic Soul","Posessed Mummy","Bandit"},5000)if e then EquipWeapon(wp)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false if e:FindFirstChild("Humanoid")then e.Humanoid.WalkSpeed=0 end AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoCakePrince then pcall(function()local e=FindEnemy({"Cake Prince","Dough King"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end else local m=FindEnemy({"Baking Staff","Head Baker","Cake Guard","Cookie Crafter"},5000)if m then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=m:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(m)end t.CanCollide=false AttackNoCD()end end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoDoughKing then pcall(function()local e=FindEnemy({"Dough King"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoEliteHunter then pcall(function()local e=FindEnemy({"Diablo","Deandre","Urban"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end else CF:InvokeServer("EliteHunter")end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoSoulReaper then pcall(function()local e=FindEnemy({"Soul Reaper"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoTyrant then pcall(function()local e=FindEnemy({"Tyrant of the Skies"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end else FarmTP(CFrame.new(-16557,202,508),getgenv().FarmSpeed,30)end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoCitizen then pcall(function()local e=FindEnemy({"Stone","Island Empress","Kilo Admiral","Captain Elephant","Beautiful Pirate"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end else FarmTP(CFrame.new(-11893.7,929.661,-8760.59),getgenv().FarmSpeed,30)CF:InvokeServer("HornedMan","Bet")end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.AutoDragonHunter then pcall(function()local e=FindEnemy({"Hydra Enforcer","Venomous Assailant"},99999)if e then EquipWeapon(S.SelectedWeapon)AutoHaki()local t=e:FindFirstChild("HumanoidRootPart")if t then FarmTP(t.CFrame*CFrame.new(0,15,0),getgenv().FarmSpeed,20)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end else local em=WS:FindFirstChild("EmberTemplate")if em and em:FindFirstChild("Part")then FarmTP(em.Part.CFrame,getgenv().FarmSpeed,30)else FarmTP(CFrame.new(5863.68,1209.87,809.94),getgenv().FarmSpeed,30)end end end)end end end)
task.spawn(function()while task.wait(0.5)do if S.AutoFarmSea then pcall(function()local tg={}if S.AutoShark then table.insert(tg,"Shark")end if S.AutoPiranha then table.insert(tg,"Piranha")end if S.AutoTerrorshark then table.insert(tg,"Terrorshark")end if S.AutoFishCrew then table.insert(tg,"Fish Crew Member")end if S.AutoSeaBeast then table.insert(tg,"SeaBeast1")end if#tg>0 then local e=FindEnemy(tg,3000)if e then local t=e:FindFirstChild("HumanoidRootPart")or e:FindFirstChild("VehicleSeat")if t then EquipWeapon(S.SelectedWeapon)AutoHaki()FarmTP(t.CFrame*CFrame.new(0,55,0),getgenv().FarmSpeed,30)if S.BringMob then BringMob(e)end t.CanCollide=false AttackNoCD()end end end end)end end end)
task.spawn(function()while task.wait(0.3)do if S.ProtectBoat then pcall(function()local b=WS:FindFirstChild("Boats")if not b then return end for _,bp in ipairs(b:GetChildren())do local o=bp:FindFirstChild("Owner")if o and tostring(o.Value)==P.Name then local st=bp:FindFirstChild("VehicleSeat")if st then local h=P.Character and P.Character:FindFirstChildOfClass("Humanoid")if h and not h.Sit then local sv=st.CFrame st.CFrame=sv+Vector3.new(math.random(75,100),math.random(75,100),math.random(75,100))end end end end end)end end end)
task.spawn(function()while task.wait(1.5)do pcall(function()if getgenv().FindMirage then local l=WS._WorldOrigin.Locations local m=l:FindFirstChild("Mirage Island")if m then FarmTP(m.CFrame*CFrame.new(0,100,0),getgenv().FarmSpeed,30)end end if getgenv().FindPrehistoric then local p2=WS.Map:FindFirstChild("PrehistoricIsland")if p2 then FarmTP(p2:GetPivot()*CFrame.new(0,100,0),getgenv().FarmSpeed,30)end end if getgenv().FindFrozen then local l=WS._WorldOrigin.Locations local f=l:FindFirstChild("Frozen Dimension")if f then FarmTP(f.CFrame*CFrame.new(0,100,0),getgenv().FarmSpeed,30)end end if getgenv().FindKitsune then local k=WS.Map:FindFirstChild("KitsuneIsland")if k and k:FindFirstChild("ShrineActive")then local p3=k.ShrineActive:FindFirstChild("NeonShrinePart")if p3 then FarmTP(p3.CFrame*CFrame.new(0,40,10),getgenv().FarmSpeed,30)end end end end)end end)
task.spawn(function()while task.wait(0.5)do pcall(function()for p,bb in pairs(S.ESPObj)do if not p.Parent or not bb.Parent then pcall(function()bb:Destroy()end)S.ESPObj[p]=nil end end local h=HRP()if not h then return end local mp=h.Position if S.ESPPlayer then for _,pl in ipairs(Players:GetPlayers())do if pl~=P and pl.Character then local t=pl.Character:FindFirstChild("HumanoidRootPart")if t then local d=math.floor((t.Position-mp).Magnitude/3)CESP(t,"[ "..pl.Name.." ] [ "..d.." ]",Color3.fromRGB(255,100,100))end end end end if S.ESPFruit then for _,o in ipairs(WS:GetChildren())do if(o:IsA("Tool")or o:IsA("Model"))and o.Name:find("Fruit")then local hd=o:FindFirstChild("Handle")or o.PrimaryPart if hd then local d=math.floor((hd.Position-mp).Magnitude/3)CESP(hd,"[ "..o.Name.." ] [ "..d.." ]",Color3.fromRGB(255,200,80))end end end end if S.ESPChest then local ch=GSC()for _,c in ipairs(ch)do if c.Parent then local d=math.floor((c.Position-mp).Magnitude/3)CESP(c,"[ Chest ] [ "..d.." ]",Color3.fromRGB(255,215,0))end end end if S.ESPBoss then local en=WS:FindFirstChild("Enemies")if en then for _,e in ipairs(en:GetChildren())do local hu=e:FindFirstChildOfClass("Humanoid")if hu and hu.DisplayName and hu.DisplayName:find("Boss")then local t=e:FindFirstChild("HumanoidRootPart")if t then local d=math.floor((t.Position-mp).Magnitude/3)CESP(t,"[ BOSS "..e.Name.." ] [ "..d.." ]",Color3.fromRGB(255,50,50))end end end end end end)end end)
RS2.Stepped:Connect(function()if S.Noclip and P.Character then pcall(function()for _,v in pairs(P.Character:GetDescendants())do if v:IsA("BasePart")then v.CanCollide=false end end end)end end)
task.spawn(function()while task.wait(1)do if S.AutoKen then pcall(function()CF:InvokeServer("Ken",true)end)end end end)
task.spawn(function()while task.wait(0.5)do if S.RemoveDamage then pcall(function()RS.Assets.GUI.DamageCounter.Enabled=false end)end if S.RemoveNotifications then pcall(function()PG.Notifications.Enabled=false end)end end end)
task.spawn(function()while task.wait(1)do if S.AutoStats then pcall(function()local d=P:FindFirstChild("Data")if not d then return end local pts=d:FindFirstChild("Points")if not pts or pts.Value<=0 then return end local as={}if S.StatMelee and S.StatMelee>0 then table.insert(as,{Name="Melee",Weight=S.StatMelee})end if S.StatSword and S.StatSword>0 then table.insert(as,{Name="Sword",Weight=S.StatSword})end if S.StatGun and S.StatGun>0 then table.insert(as,{Name="Gun",Weight=S.StatGun})end if S.StatFruit and S.StatFruit>0 then table.insert(as,{Name="Demon Fruit",Weight=S.StatFruit})end if#as==0 then return end local tw=0 for _,s in ipairs(as)do tw=tw+s.Weight end local tp=pts.Value for _,s in ipairs(as)do if tp<=0 then break end local sh=math.floor(tp*(s.Weight/tw))if sh<=0 then sh=1 end if sh>tp then sh=tp end pcall(function()CF:InvokeServer("AddPoint",s.Name,sh)end)tp=tp-sh task.wait(0.2)end end)end end end)
task.spawn(function()while task.wait(0.1)do pcall(function()local h=P.Character and P.Character:FindFirstChildOfClass("Humanoid")if h then if getgenv().EnableWalkSpeed and h.WalkSpeed~=getgenv().CustomWalkSpeed then h.WalkSpeed=getgenv().CustomWalkSpeed end if getgenv().EnableJumpPower and h.JumpPower~=getgenv().CustomJumpPower then h.JumpPower=getgenv().CustomJumpPower end end end)end end)
UIS.JumpRequest:Connect(function()if getgenv().InfiniteJump then local h=P.Character and P.Character:FindFirstChildOfClass("Humanoid")if h then h:ChangeState(Enum.HumanoidStateType.Jumping)end end end)
P.Idled:Connect(function()if S.AntiAFK then VU:CaptureController()VU:ClickButton2(Vector2.new())end end)
task.spawn(function()while task.wait(0.3)do if S.TeleportPlayer and S.SelectedPlayer then pcall(function()local pl=Players:FindFirstChild(S.SelectedPlayer)if pl and pl.Character and pl.Character:FindFirstChild("HumanoidRootPart")then FarmTP(pl.Character.HumanoidRootPart.CFrame,getgenv().FarmSpeed,30)end end)end end end)
do local dg,ds,spp=false,nil,nil HD.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=true ds=i.Position spp=M.Position end end)UIS.InputChanged:Connect(function(i)if not dg then return end if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then local d=i.Position-ds M.Position=UDim2.new(spp.X.Scale,spp.X.Offset+d.X,spp.Y.Scale,spp.Y.Offset+d.Y)end end)UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=false end end)end
CL.Activated:Connect(function()G.Enabled=false Notify("UI Hidden - Tap 'SX' logo")end)
STab("Farm")
Notify("SysxHub v2.4 Loaded - Tap 'SX' logo ✅")
