-- SysxHub v1.9.2 | 1 File | Discord: https://discord.gg/E5kQJW3hn
local RS=game:GetService("ReplicatedStorage")
local RunSvc=game:GetService("RunService")
local Players=game:GetService("Players")
if RunSvc:IsServer()then
local root=RS:FindFirstChild("SysxHub")or(function()local f=Instance.new("Folder")f.Name="SysxHub"f.Parent=RS return f end)()
local rem=root:FindFirstChild("Remotes")or(function()local f=Instance.new("Folder")f.Name="Remotes"f.Parent=root return f end)()
for _,n in ipairs({"Farm","Chest","Boss","Material","Sea","Quest","Raid","Fishing","PvP","Stats","Combat","Misc","Discord","Status","Fruit"})do if not rem:FindFirstChild(n)then local r=Instance.new("RemoteEvent")r.Name=n r.Parent=rem end end
local R=function(n)return rem:FindFirstChild(n)end
R("Combat").OnServerEvent:Connect(function(p,a,d)if a=="Attack"then local c=p.Character if c then local t=c:FindFirstChildOfClass("Tool")if t then pcall(function()t:Activate()end)end end end end)
R("Farm").OnServerEvent:Connect(function(p,a,d)if a=="start"then p:SetAttribute("AFarm",true)task.spawn(function()while p:GetAttribute("AFarm")do local c=p.Character if c and c:FindFirstChild("HumanoidRootPart")then local pos=c.HumanoidRootPart.Position local n,dst=nil,math.huge for _,m in ipairs(workspace:GetDescendants())do if m:IsA("Model")and m:FindFirstChild("Humanoid")and m.Humanoid.Health>0 and m~=c then local r2=m:FindFirstChild("HumanoidRootPart")or m.PrimaryPart if r2 then local dd=(r2.Position-pos).Magnitude if dd<dst and dd<500 then n,dst=m,dd end end end end if n then local r2=n:FindFirstChild("HumanoidRootPart")or n.PrimaryPart if r2 then c:PivotTo(r2.CFrame*CFrame.new(0,0,4))end local t=c:FindFirstChildOfClass("Tool")if t then pcall(function()t:Activate()end)end end end task.wait(0.35)end end)elseif a=="stop"then p:SetAttribute("AFarm",false)elseif a=="setTool"then p:SetAttribute("Tool",d.tool)end end)
local cc={}
R("Chest").OnServerEvent:Connect(function(p,a,d)if a=="start"then p:SetAttribute("AChest",true)task.spawn(function()local op=0 while p:GetAttribute("AChest")do local c=p.Character if not c or not c:FindFirstChild("HumanoidRootPart")then task.wait(0.5)else local pos=c.HumanoidRootPart.Position local rng=p:GetAttribute("CRange")or 200 local ch,dst=nil,math.huge for _,o in ipairs(workspace:GetDescendants())do if o:IsA("Model")and o.Name:lower():find("chest")and not o:GetAttribute("Opened")then local pp=o:FindFirstChild("HumanoidRootPart")or o.PrimaryPart if pp then local dd=(pp.Position-pos).Magnitude if dd<dst and dd<rng then ch,dst=o,dd end end end end if ch then local pp=ch:FindFirstChild("HumanoidRootPart")or ch.PrimaryPart if pp then c:PivotTo(pp.CFrame+Vector3.new(0,3,0))end task.wait(0.4)for _,dd in ipairs(ch:GetDescendants())do if dd:IsA("ProximityPrompt")then dd:InputHoldBegin()task.wait(dd.HoldDuration or 0.2)dd:InputHoldEnd()break end end ch:SetAttribute("Opened",true)op=op+1 cc[p]=op R("Chest"):FireClient(p,"count",op)local its={"Sword","Money","Fruit","Material","Potion"}local got=its[math.random(1,#its)]R("Chest"):FireClient(p,"lastItem",got)if p:GetAttribute("CStop")and got~="Money"then p:SetAttribute("AChest",false)R("Chest"):FireClient(p,"stop",got)break end end task.wait(p:GetAttribute("CSpeed")or 0.5)end end end)elseif a=="stop"then p:SetAttribute("AChest",false)elseif a=="stopWhenItem"then p:SetAttribute("CStop",d.enable)elseif a=="setRange"then p:SetAttribute("CRange",d.value)elseif a=="setSpeed"then p:SetAttribute("CSpeed",d.value)end end)
Players.PlayerRemoving:Connect(function(p)cc[p]=nil end)
local FRUITS={{n="Rocket",w=60,r="Common"},{n="Spin",w=60,r="Common"},{n="Blade",w=55,r="Common"},{n="Spring",w=50,r="Common"},{n="Bomb",w=50,r="Common"},{n="Smoke",w=45,r="Common"},{n="Flame",w=25,r="Uncommon"},{n="Ice",w=25,r="Uncommon"},{n="Sand",w=25,r="Uncommon"},{n="Dark",w=20,r="Uncommon"},{n="Diamond",w=18,r="Uncommon"},{n="Light",w=12,r="Rare"},{n="Rubber",w=10,r="Rare"},{n="Barrier",w=8,r="Rare"},{n="Magma",w=6,r="Epic"},{n="Door",w=5,r="Epic"},{n="Buddha",w=3,r="Epic"},{n="Love",w=3,r="Epic"},{n="Spider",w=2,r="Legendary"},{n="Sound",w=2,r="Legendary"},{n="Phoenix",w=2,r="Legendary"},{n="Portal",w=1.5,r="Legendary"},{n="Rumble",w=1.5,r="Legendary"},{n="Pain",w=1,r="Legendary"},{n="Blizzard",w=1,r="Legendary"},{n="Gravity",w=0.5,r="Mythical"},{n="Shadow",w=0.5,r="Mythical"},{n="Dough",w=0.3,r="Mythical"},{n="Control",w=0.2,r="Mythical"},{n="Spirit",w=0.15,r="Mythical"},{n="Dragon",w=0.05,r="Mythical"},{n="Leopard",w=0.03,r="Mythical"},{n="Kitsune",w=0.01,r="Mythical"}}
local function rollF()local tot=0 for _,f in ipairs(FRUITS)do tot=tot+f.w end local rr=math.random()*tot local c=0 for _,f in ipairs(FRUITS)do c=c+f.w if rr<=c then return f end end return FRUITS[#FRUITS]end
local rC={}
R("Raid").OnServerEvent:Connect(function(p,a,d)
if a=="rolled"then local am=math.clamp(tonumber(d.amount)or 1,1,10)for i=1,am do local g=rollF()local bp=p:FindFirstChild("Backpack")if bp then local tpl=RS:FindFirstChild("FruitTemplates")and RS.FruitTemplates:FindFirstChild(g.n)if tpl then local t=tpl:Clone()t.Parent=bp end end R("Raid"):FireClient(p,"rolled",{name=g.n,rarity=g.r})task.wait(0.3)end rC[p]=(rC[p]or 0)+am R("Raid"):FireClient(p,"rollCount",rC[p])
elseif a=="selectChip"then p:SetAttribute("Chip",d.chip)
elseif a=="start"then p:SetAttribute("AutoRaid",true)
elseif a=="stop"then p:SetAttribute("AutoRaid",false)end end)
R("Fruit").OnServerEvent:Connect(function(p,a,d)if a=="store"then local nm=d and d.item if type(nm)~="string"then return end local ch=p.Character local bp=p:FindFirstChild("Backpack")if not ch or not bp then return end local src=nil for _,t in ipairs(ch:GetChildren())do if t:IsA("Tool")and t.Name==nm then src=t break end end if not src then for _,t in ipairs(bp:GetChildren())do if t:IsA("Tool")and t.Name==nm then src=t break end end end if not src then return end local st=p:FindFirstChild("Storage")if not st then st=Instance.new("Folder")st.Name="Storage"st.Parent=p end src.Parent=st R("Fruit"):FireClient(p,"stored",{item=nm})end end)
Players.PlayerRemoving:Connect(function(p)rC[p]=nil end)
local VC={}
R("Misc").OnServerEvent:Connect(function(p,a,d)if a=="redeem"then local c=d and d.code if type(c)~="string"then return end local now=tick()VC[p]=VC[p]or 0 if now-VC[p]<0.5 then return end VC[p]=now local f=p:FindFirstChild("Redeemed")if not f then f=Instance.new("Folder")f.Name="Redeemed"f.Parent=p end if f:FindFirstChild(c)then return end Instance.new("BoolValue",f).Name=c R("Misc"):FireClient(p,"redeemResult",{code=c,ok=true})elseif a=="checkMap"then R("Misc"):FireClient(p,"fruitStatus",false)R("Misc"):FireClient(p,"mapStatus","OK")end end)
Players.PlayerRemoving:Connect(function(p)VC[p]=nil end)
print("[SysxHub] Server v1.9.2 OK")
end
if RunSvc:IsClient()then
local UIS=game:GetService("UserInputService")
local Tw=game:GetService("TweenService")
local TS=game:GetService("TeleportService")
local Plr=Players.LocalPlayer
local Br={Name="SysxHub",Discord="https://discord.gg/E5kQJW3hn",Asset="rbxassetid://70792832229220",Ver="1.9.2"}
local T={Bg=Color3.fromRGB(16,8,24),Bg2=Color3.fromRGB(24,13,35),BgG=Color3.fromRGB(38,18,58),Pn=Color3.fromRGB(31,17,45),Pn2=Color3.fromRGB(42,23,60),Pr=Color3.fromRGB(118,52,180),PrD=Color3.fromRGB(72,28,112),PrL=Color3.fromRGB(160,85,225),Pink=Color3.fromRGB(210,90,200),Tx=Color3.fromRGB(245,240,250),Tx2=Color3.fromRGB(180,165,195),St=Color3.fromRGB(85,48,110),Ok=Color3.fromRGB(100,210,140),Wn=Color3.fromRGB(230,190,80),Er=Color3.fromRGB(220,80,100)}
local CFG={W=680,H=500,SW=160,TH=54,CR=12,SO={0.75,0.85,1.0,1.10,1.25},Tabs={"Discord","Farm","Boss","Material","Sea","Quests / Items","Fruit / Raid","Fishing","Status","PvP","Stats","Misc"}}
local S={Tool="Melee",Sea=1,Boss=nil,Mat=nil,SeaMob=nil,Plr=nil,Chip=nil,SQ=nil,SQI=nil,Tg={}}
local U={}
function U.mk(c,p,par)local o=Instance.new(c)for k,v in pairs(p or{})do o[k]=v end if par then o.Parent=par end return o end
function U.cr(o,r)return U.mk("UICorner",{CornerRadius=UDim.new(0,r or CFG.CR)},o)end
function U.st(o,c,t)return U.mk("UIStroke",{Color=c or T.St,Thickness=t or 1,ApplyStrokeMode=Enum.ApplyStrokeMode.Border},o)end
function U.pd(o,p)local x=U.mk("UIPadding",{},o)local u=UDim.new(0,p or 8)x.PaddingTop,x.PaddingBottom,x.PaddingLeft,x.PaddingRight=u,u,u,u return x end
function U.gd(o,a,b,r)return U.mk("UIGradient",{Color=ColorSequence.new(a,b),Rotation=r or 90},o)end
function U.tn(o,t,k)local w=Tw:Create(o,t,k)w:Play()return w end
function U.tr(f,e)local o,x=pcall(f)if not o and e then e(x)end return o,x end
local D={}
D.Tools={"Melee","Sword","Gun","Blox Fruit"}
D.Chips={"Flame Chip","Ice Chip","Quake Chip","Light Chip"}
D.Codes={"SUB2GAMERROBOT_EXP1","EASTEREXP","KittGaming","Sub2CaptainMaui","Sub2OfficialNoobie","Sub2Fer999","Enyu_is_Pro","JCWK","StarcodeHEO","MagicBUS","TheGreatAce","Sub2NoobMaster123","Sub2Daigrock","Axiore","StrawHatMaine","TantaiGaming","Bluxxy","KITT_RESET","Sub2UncleKizaru","SUB2GAMERROBOT_RESET1","BIGNEWS","fudd10_V2","fudd10","CHANDLER"}
D.Mat={["Bones"]={"Skeleton","Jungle",1,"Common",5},["Ectoplasm"]={"Ghost","Graveyard",2,"Uncommon",200},["Gunpowder"]={"Pirate","Pirate Village",1,"Common",10},["Scrap Metal"]={"Dock Worker","Port Town",3,"Common",700},["Leather"]={"Bandit","Starter Island",1,"Common",1},["Magma Ore"]={"Magma Beast","Magma Village",1,"Rare",90},["Fish Tail"]={"Sea Serpent","Underwater City",1,"Uncommon",110},["Mystic Droplet"]={"Fountain Spirit","Fountain City",1,"Rare",130},["Vampire Fang"]={"Haunted Knight","Haunted Castle",3,"Epic",1200},["Radioactive Material"]={"Mutant Beast","Green Zone",2,"Epic",175},["Shark Tooth"]={"Shark","Underwater City",1,"Uncommon",110},["Conjured Cocoa"]={"Candy Monster","Sea of Treats",3,"Rare",1400},["Demonic Wisp"]={"Dark Knight","Dark Arena",2,"Epic",250},["Dragon Scale"]={"Hydra Head","Hydra Island",3,"Legendary",800},["Electric Wing"]={"Sky Warrior","Skylands",1,"Rare",40},["Mutant Tooth"]={"Mutant Beast","Forgotten Island",2,"Legendary",500}}
D.Bosses={"Gorilla King","Bobby","The Saw","Yeti","Vice Admiral","Saber Expert","Warden","Chief Warden","Swan","Magma Admiral","Fishman Lord","Wysper","Thunder God","Cyborg","Don Swan","Darkbeard","Order","Cursed Captain","Awakened Ice Admiral","Stone","Hydra Leader","Kilo Admiral","Captain Elephant","Beautiful Pirate","Longma","Cursed Skeleton","Island Empress","Cake Queen"}
D.SeaMobs={{n="Sea Beast",s=1,t="Beast",hp=8000},{n="Pirate Ship",s=1,t="Ship",hp=15000},{n="Piranha",s=1,t="Beast",hp=2500},{n="Shark",s=1,t="Beast",hp=5000},{n="FishCrew Member",s=1,t="NPC",hp=3000},{n="Cursed Ship",s=2,t="Ship",hp=60000},{n="Big Sea Beast",s=2,t="Beast",hp=100000},{n="Ghost Pirate Ship",s=2,t="Ship",hp=150000},{n="Sea Monster",s=2,t="Beast",hp=200000},{n="Terror Shark",s=3,t="Beast",hp=400000},{n="Sea Emperor",s=3,t="Boss",hp=500000},{n="Leviathan",s=3,t="Boss",hp=800000},{n="Kraken",s=3,t="Boss",hp=1000000}}
D.SQ={{i="Starter Island",n="The Finale"},{i="Jungle",n="Perbaiki Zipline"},{i="Jungle",n="Kalahkan Monyet Pencuri"},{i="Jungle",n="Jatuhkan Pisang"},{i="Pirate Village",n="Bebaskan Kincir Angin"},{i="Pirate Village",n="Usir 3 Tavern Pirates"},{i="Pirate Village",n="Masak Stew"},{i="Desert",n="Selamatkan Hasan"},{i="Desert",n="Bersihkan 8 Rune/Pilar"},{i="Desert",n="Kumpulkan 10 Cactus Petals"},{i="Frozen Village",n="Bebaskan Ability Teacher"},{i="Frozen Village",n="Buat Snowman"},{i="Frozen Village",n="Hancurkan 3 Bongkahan Es Hijau"},{i="Marine Fortress",n="Pasang Bendera"},{i="Marine Fortress",n="Pertahankan Benteng"},{i="Marine Fortress",n="Hancurkan Bangunan"},{i="Lower Skylands",n="Cari Lightning Bolt"},{i="Lower Skylands",n="Usir Penyusup"},{i="Lower Skylands",n="Pukul Secret Cloud"},{i="Prison",n="Bantu 3 Tahanan Kabur"},{i="Prison",n="Ambil Kunci & Pink Coat"},{i="Prison",n="Atur Tuas"},{i="Colosseum",n="Selesaikan 3 Wave"},{i="Colosseum",n="Aktifkan 4 Patung"},{i="Colosseum",n="Hancurkan 18 Target 90s"},{i="Magma Village",n="Hadapi Gelombang Magma"},{i="Magma Village",n="Hancurkan Magma Drill"},{i="Magma Village",n="Hancurkan 5 Mini Lava Geyser"},{i="Underwater City",n="Naiki Bubble"},{i="Underwater City",n="Atur Crystal"},{i="Underwater City",n="Cari Black Pearl"},{i="Upper Skylands",n="Ambil Relic"},{i="Upper Skylands",n="Serang Awan Petir"},{i="Upper Skylands",n="Bunyikan Bell 6 Kali"},{i="Fountain City",n="Perbaiki Pipa Fountain"},{i="Fountain City",n="Kalahkan Megalo Brute"},{i="Fountain City",n="Perbaiki Kabel Junkyard"}}
local root=RS:WaitForChild("SysxHub")
local rem=root:WaitForChild("Remotes")
local R=function(n)return rem:FindFirstChild(n)end
local fire=function(n,a,d)local r=R(n)if r then r:FireServer(a,d or{})end end
local Nf={}local nH
local function nCol(k)if k=="SUCCESS"then return T.Ok end if k=="WARNING"then return T.Wn end if k=="ERROR"then return T.Er end return T.PrL end
function Nf.Init(par)nH=U.mk("Frame",{Name="NH",BackgroundTransparency=1,Size=UDim2.new(0,300,1,-60),Position=UDim2.new(1,-312,0,44)},par)U.mk("UIListLayout",{Padding=UDim.new(0,6),SortOrder=Enum.SortOrder.LayoutOrder,VerticalAlignment=Enum.VerticalAlignment.Top},nH)end
function Nf.Push(k,ti,msg,d)if not nH then return end d=d or 3 local c=U.mk("Frame",{BackgroundColor3=T.Pn,BorderSizePixel=0,Size=UDim2.new(1,0,0,0),BackgroundTransparency=1},nH)U.cr(c,8)U.st(c,nCol(k))U.mk("Frame",{BackgroundColor3=nCol(k),BorderSizePixel=0,Size=UDim2.new(0,4,1,-8),Position=UDim2.new(0,4,0,4)},c)U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text=ti,TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-20,0,16),Position=UDim2.new(0,14,0,6)},c)U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text=msg,TextColor3=T.Tx2,TextSize=12,TextXAlignment=Enum.TextXAlignment.Left,TextWrapped=true,Size=UDim2.new(1,-20,0,16),Position=UDim2.new(0,14,0,22)},c)U.tn(c,TweenInfo.new(0.28,Enum.EasingStyle.Quart),{Size=UDim2.new(1,0,0,46),BackgroundTransparency=0})task.delay(d,function()if not c.Parent then return end local w=U.tn(c,TweenInfo.new(0.22),{Size=UDim2.new(1,0,0,0),BackgroundTransparency=1})w.Completed:Connect(function()c:Destroy()end)end)end
local Gui=U.mk("ScreenGui",{Name="SysxHub",ResetOnSpawn=false,IgnoreGuiInset=true,ZIndexBehavior=Enum.ZIndexBehavior.Sibling,DisplayOrder=999},Plr:WaitForChild("PlayerGui"))Nf.Init(Gui)
local Ob=U.mk("ImageButton",{Name="OpenButton",Image=Br.Asset,BackgroundTransparency=1,Size=UDim2.fromOffset(76,76),Position=UDim2.new(0,20,0.5,-38),AnchorPoint=Vector2.new(0,0),ScaleType=Enum.ScaleType.Fit},Gui)U.cr(Ob,38)U.mk("UIAspectRatioConstraint",{AspectRatio=1,AspectType=Enum.AspectType.FitWithinMaxSize,DominantAxis=Enum.DominantAxis.Width},Ob)
local M=U.mk("Frame",{Name="MW",BackgroundColor3=T.Bg,BorderSizePixel=0,Size=UDim2.fromOffset(CFG.W,CFG.H),Position=UDim2.new(0.5,-CFG.W/2,0.5,-CFG.H/2)},Gui)U.cr(M,14)U.st(M,T.St)U.gd(M,T.Bg,T.BgG,120)M.ClipsDescendants=true local Sc=U.mk("UIScale",{Scale=1},M)
local TB=U.mk("Frame",{Name="TB",BackgroundColor3=T.Bg2,BorderSizePixel=0,Size=UDim2.new(1,0,0,CFG.TH)},M)U.cr(TB,14)U.st(TB,T.St)U.gd(TB,T.PrD,T.Bg2,0)
local Lg=U.mk("ImageLabel",{Image=Br.Asset,BackgroundTransparency=1,Size=UDim2.fromOffset(60,60),Position=UDim2.new(0,6,0.5,-30),ScaleType=Enum.ScaleType.Fit},TB)U.mk("UIAspectRatioConstraint",{AspectRatio=1,AspectType=Enum.AspectType.FitWithinMaxSize,DominantAxis=Enum.DominantAxis.Width},Lg)
U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text=Br.Name,TextColor3=T.PrL,TextSize=20,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(0,200,1,0),Position=UDim2.new(0,72,0,0)},TB)
local function tBt(t,x,c)local b=U.mk("TextButton",{BackgroundColor3=c or T.Pn2,BorderSizePixel=0,Text=t,TextColor3=T.Tx,Font=Enum.Font.GothamBold,TextSize=14,AutoButtonColor=false,Size=UDim2.fromOffset(32,30),Position=UDim2.new(1,x,0.5,-15)},TB)U.cr(b,6)b.MouseEnter:Connect(function()U.tn(b,TweenInfo.new(0.15),{BackgroundColor3=T.Pr})end)b.MouseLeave:Connect(function()U.tn(b,TweenInfo.new(0.15),{BackgroundColor3=c or T.Pn2})end)return b end
local ScaleBtn=tBt("◱",-108)local MinBtn=tBt("—",-72)local ClsBtn=tBt("✕",-36,T.Er)
local Sb=U.mk("Frame",{BackgroundColor3=T.Bg2,BorderSizePixel=0,Size=UDim2.new(0,CFG.SW,1,-CFG.TH),Position=UDim2.new(0,0,0,CFG.TH)},M)U.st(Sb,T.St)
local SLH=U.mk("Frame",{BackgroundColor3=T.Bg,BorderSizePixel=0,Size=UDim2.new(1,-12,0,112),Position=UDim2.new(0,6,0,6)},Sb)U.cr(SLH,10)
local SLg=U.mk("ImageLabel",{Image=Br.Asset,BackgroundTransparency=1,Size=UDim2.fromOffset(100,100),Position=UDim2.new(0.5,0,0.5,0),AnchorPoint=Vector2.new(0.5,0.5),ScaleType=Enum.ScaleType.Fit},SLH)U.mk("UIAspectRatioConstraint",{AspectRatio=1,AspectType=Enum.AspectType.FitWithinMaxSize,DominantAxis=Enum.DominantAxis.Width},SLg)
local SSb=U.mk("ScrollingFrame",{BackgroundTransparency=1,BorderSizePixel=0,Size=UDim2.new(1,0,1,-124),Position=UDim2.new(0,0,0,124),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=3,ScrollBarImageColor3=T.Pr},Sb)U.mk("UIListLayout",{Padding=UDim.new(0,4),SortOrder=Enum.SortOrder.LayoutOrder},SSb)U.pd(SSb,6)
local Ct=U.mk("Frame",{BackgroundColor3=T.Bg,BorderSizePixel=0,Size=UDim2.new(1,-CFG.SW,1,-CFG.TH),Position=UDim2.new(0,CFG.SW,0,CFG.TH)},M)
local SR=U.mk("TextBox",{BackgroundColor3=T.Bg2,BorderSizePixel=0,ClearTextOnFocus=false,PlaceholderText="Search Feature...",PlaceholderColor3=T.Tx2,TextColor3=T.Tx,Font=Enum.Font.Gotham,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Text="",Size=UDim2.new(1,-24,0,34),Position=UDim2.new(0,12,0,10)},Ct)U.cr(SR,6)U.st(SR)U.pd(SR,8)
local CS=U.mk("ScrollingFrame",{BackgroundTransparency=1,BorderSizePixel=0,Size=UDim2.new(1,-16,1,-60),Position=UDim2.new(0,8,0,54),CanvasSize=UDim2.new(0,0,0,0),AutomaticCanvasSize=Enum.AutomaticSize.Y,ScrollBarThickness=4,ScrollBarImageColor3=T.Pr},Ct)U.mk("UIListLayout",{Padding=UDim.new(0,6),SortOrder=Enum.SortOrder.LayoutOrder},CS)U.pd(CS,8)
local CM={l={}}
function CM:add(c)table.insert(self.l,c)end
function CM:clr()for _,c in ipairs(self.l)do pcall(function()c:Disconnect()end)end self.l={}end
local cT,reg=nil,{}
local function clrC()CM:clr()for _,c in ipairs(CS:GetChildren())do if c:IsA("GuiObject")then c:Destroy()end end reg={}end
local function secL(t,o)local l=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text="▸ "..t,TextColor3=T.PrL,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,22)},CS)l.LayoutOrder=o or 0 table.insert(reg,{cT,t,l})return l end
local function mkTg(t,k,d,cb,o)local r=U.mk("Frame",{BackgroundColor3=T.Pn,BorderSizePixel=0,Size=UDim2.new(1,-8,0,38)},CS)r.LayoutOrder=o or 0 U.cr(r,10)U.st(r)U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamMedium,Text=t,TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-80,1,0),Position=UDim2.new(0,12,0,0)},r)local st=S.Tg[k]if st==nil then st=d or false end local tr=U.mk("Frame",{BackgroundColor3=st and T.PrL or T.Pn2,BorderSizePixel=0,Size=UDim2.fromOffset(46,22),Position=UDim2.new(1,-58,0.5,-11)},r)U.cr(tr,11)U.st(tr)local kn=U.mk("Frame",{BackgroundColor3=T.Tx,BorderSizePixel=0,Size=UDim2.fromOffset(18,18),Position=st and UDim2.new(1,-20,0.5,-9)or UDim2.new(0,2,0.5,-9)},tr)U.cr(kn,9)local bt=U.mk("TextButton",{BackgroundTransparency=1,Text="",Size=UDim2.new(1,0,1,0)},r)CM:add(bt.MouseButton1Click:Connect(function()st=not st S.Tg[k]=st local ti=TweenInfo.new(0.18,Enum.EasingStyle.Quart)U.tn(tr,ti,{BackgroundColor3=st and T.PrL or T.Pn2})U.tn(kn,ti,{Position=st and UDim2.new(1,-20,0.5,-9)or UDim2.new(0,2,0.5,-9)})if cb then U.tr(function()cb(st)end,function(e)Nf.Push("ERROR","Toggle",tostring(e),3)end)end end))table.insert(reg,{cT,t,r})return r end
local function mkBt(t,cb,o)local b=U.mk("TextButton",{BackgroundColor3=T.Pn,BorderSizePixel=0,Text=t,TextColor3=T.Tx,Font=Enum.Font.GothamMedium,TextSize=13,AutoButtonColor=false,Size=UDim2.new(1,-8,0,36)},CS)b.LayoutOrder=o or 0 U.cr(b,8)U.st(b)CM:add(b.MouseEnter:Connect(function()U.tn(b,TweenInfo.new(0.15),{BackgroundColor3=T.Pn2})end))CM:add(b.MouseLeave:Connect(function()U.tn(b,TweenInfo.new(0.15),{BackgroundColor3=T.Pn})end))CM:add(b.MouseButton1Click:Connect(function()if cb then U.tr(cb)end end))table.insert(reg,{cT,t,b})return b end
local function mkSl(t,mn,mx,d,cb,o)local r=U.mk("Frame",{BackgroundColor3=T.Pn,BorderSizePixel=0,Size=UDim2.new(1,-8,0,50)},CS)r.LayoutOrder=o or 0 U.cr(r,8)U.st(r)U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamMedium,Text=t,TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-80,0,18),Position=UDim2.new(0,12,0,4)},r)local vl=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text=string.format("%.0f",d),TextColor3=T.PrL,TextSize=13,TextXAlignment=Enum.TextXAlignment.Right,Size=UDim2.new(0,66,0,18),Position=UDim2.new(1,-78,0,4)},r)local br=U.mk("Frame",{BackgroundColor3=T.Bg2,BorderSizePixel=0,Size=UDim2.new(1,-24,0,8),Position=UDim2.new(0,12,0,32)},r)U.cr(br,4)U.st(br)local fl=U.mk("Frame",{BackgroundColor3=T.PrL,BorderSizePixel=0,Size=UDim2.new((d-mn)/(mx-mn),0,1,0)},br)U.cr(fl,4)U.gd(fl,T.PrL,T.Pink,0)local kn=U.mk("Frame",{BackgroundColor3=T.Tx,BorderSizePixel=0,Size=UDim2.fromOffset(14,14),Position=UDim2.new((d-mn)/(mx-mn),-7,0.5,-7)},br)U.cr(kn,7)local dg=false local function sX(x)local rr=math.clamp((x-br.AbsolutePosition.X)/br.AbsoluteSize.X,0,1)local v=mn+(mx-mn)*rr fl.Size=UDim2.new(rr,0,1,0)kn.Position=UDim2.new(rr,-7,0.5,-7)vl.Text=string.format("%.0f",v)if cb then U.tr(function()cb(v)end)end end CM:add(br.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=true sX(i.Position.X)end end))CM:add(UIS.InputChanged:Connect(function(i)if dg and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then sX(i.Position.X)end end))CM:add(UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dg=false end end))table.insert(reg,{cT,t,r})return r end
local function mkDd(lb,opt,cb,o,sk)local h=U.mk("Frame",{BackgroundColor3=T.Pn,BorderSizePixel=0,Size=UDim2.new(1,-8,0,38)},CS)h.LayoutOrder=o or 0 U.cr(h,8)U.st(h)h.ClipsDescendants=true local it=(sk and S[sk])or opt[1]or"-" local hd=U.mk("TextButton",{BackgroundColor3=T.Pn,BorderSizePixel=0,Text="  "..lb..": "..tostring(it),TextColor3=T.Tx,Font=Enum.Font.GothamMedium,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,AutoButtonColor=false,Size=UDim2.new(1,0,0,38)},h)local lh=U.mk("Frame",{BackgroundColor3=T.Bg2,BorderSizePixel=0,Size=UDim2.new(1,-16,0,0),Position=UDim2.new(0,8,0,40)},h)U.cr(lh,6)lh.ClipsDescendants=true U.mk("UIListLayout",{Padding=UDim.new(0,2),SortOrder=Enum.SortOrder.LayoutOrder},lh)local op=false for i,v in ipairs(opt)do local ib=U.mk("TextButton",{BackgroundColor3=T.Pn,BorderSizePixel=0,Text="  "..v,TextColor3=T.Tx,Font=Enum.Font.Gotham,TextSize=12,TextXAlignment=Enum.TextXAlignment.Left,AutoButtonColor=false,Size=UDim2.new(1,-8,0,28),LayoutOrder=i},lh)U.cr(ib,4)CM:add(ib.MouseEnter:Connect(function()U.tn(ib,TweenInfo.new(0.12),{BackgroundColor3=T.Pn2})end))CM:add(ib.MouseLeave:Connect(function()U.tn(ib,TweenInfo.new(0.12),{BackgroundColor3=T.Pn})end))CM:add(ib.MouseButton1Click:Connect(function()hd.Text="  "..lb..": "..v if sk then S[sk]=v end op=false U.tn(h,TweenInfo.new(0.2),{Size=UDim2.new(1,-8,0,38)})U.tn(lh,TweenInfo.new(0.2),{Size=UDim2.new(1,-16,0,0)})if cb then U.tr(function()cb(v)end)end end))end CM:add(hd.MouseButton1Click:Connect(function()op=not op local hh=math.min(#opt*30+8,180)U.tn(h,TweenInfo.new(0.2),{Size=UDim2.new(1,-8,0,op and 38+hh+8 or 38)})U.tn(lh,TweenInfo.new(0.2),{Size=UDim2.new(1,-16,0,op and hh or 0)})end))CM:add(UIS.InputBegan:Connect(function(i)if not op then return end if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then op=false U.tn(h,TweenInfo.new(0.2),{Size=UDim2.new(1,-8,0,38)})U.tn(lh,TweenInfo.new(0.2),{Size=UDim2.new(1,-16,0,0)})end end))table.insert(reg,{cT,lb,h})return h end
local function mkI(o,ht)local h=U.mk("Frame",{BackgroundColor3=T.Pn,BorderSizePixel=0,Size=UDim2.new(1,-8,0,ht or 100)},CS)h.LayoutOrder=o or 0 U.cr(h,8)U.st(h)return h end
local function fI(h,ls)for _,c in ipairs(h:GetChildren())do if c:IsA("GuiObject")then c:Destroy()end end U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text=table.concat(ls,"\n"),TextColor3=T.Tx,TextSize=12,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,TextWrapped=true,Size=UDim2.new(1,-16,1,-16),Position=UDim2.new(0,8,0,8)},h)end
local Cb={run=false,tg={H=false,K=false,A=false}}
local function cGo()if Cb.run then return end Cb.run=true task.spawn(function()while Cb.run do if Cb.tg.A then fire("Combat","Attack",{})end task.wait(0.35)end end)end
local function cStop()Cb.run=false end
local aimOn=false local aimTarget=nil local cam=workspace.CurrentCamera
RunSvc.RenderStepped:Connect(function(dt)if aimOn and aimTarget then local t=Players:FindFirstChild(aimTarget)if t and t.Character then local hrp=t.Character:FindFirstChild("HumanoidRootPart")if hrp then local d=(hrp.Position-cam.CFrame.Position).Magnitude if d<300 then local want=CFrame.lookAt(cam.CFrame.Position,hrp.Position)cam.CFrame=cam.CFrame:Lerp(want,1-math.exp(-10*dt))end end end end end)
local TBU={}
TBU["Discord"]=function()secL("Community",1)mkBt("Join Discord — "..Br.Discord,function()if setclipboard then pcall(setclipboard,Br.Discord)end Nf.Push("SUCCESS","Discord",Br.Discord,3)end,2)secL("Info",3)mkBt("Version: "..Br.Ver,function()end,4)mkBt("Copy Asset Toggle ID",function()if setclipboard then pcall(setclipboard,"70792832229220")end Nf.Push("SUCCESS","Asset","Copied",2)end,5)end
TBU["Farm"]=function()secL("Farm Config",1)mkDd("Select Tool",D.Tools,function(v)fire("Farm","setTool",{tool=v})end,2,"Tool")mkSl("UI Scale",0.5,1.5,1.0,function(v)Sc.Scale=v end,3)secL("Auto Farm",10)local o=11 local function ft(n,k)mkTg(n,"F_"..k,false,function(on)fire("Farm",on and"start"or"stop",{enable=on})Nf.Push(on and"SUCCESS"or"INFO",n,on and"ON"or"OFF",2)end,o)o=o+1 end ft("Auto Farm Level","L")ft("Auto Farm Nearest","N")ft("Auto Factory","Fa")ft("Auto Farm Ectoplasm","E")ft("Auto Accept Quest","Q")secL("Chest Farm",20)o=21 mkTg("Auto Farm Chest","AC",false,function(on)fire("Chest",on and"start"or"stop",{enable=on})Nf.Push(on and"SUCCESS"or"INFO","Chest",on and"ON"or"OFF",2)end,o);o=o+1 mkTg("Stop When Get Item in Chest","CSI",false,function(on)fire("Chest","stopWhenItem",{enable=on})end,o);o=o+1 mkSl("Max Chest Range",50,500,200,function(v)fire("Chest","setRange",{value=v})end,o);o=o+1 mkSl("Farm Speed",0.1,2.0,0.5,function(v)fire("Chest","setSpeed",{value=v})end,o);o=o+1 local cl=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Chests Opened: 0",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)cl.LayoutOrder=o;o=o+1 local il=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Last Item: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)il.LayoutOrder=o;o=o+1 local cr=R("Chest")if cr then CM:add(cr.OnClientEvent:Connect(function(k,d)if k=="count"then cl.Text="Chests Opened: "..tostring(d)elseif k=="lastItem"then il.Text="Last Item: "..tostring(d)end end))end secL("Combat",40)o=41 mkTg("Auto Haki","CH",false,function(on)Cb.tg.H=on fire("Combat","Haki",{enable=on})end,o);o=o+1 mkTg("Auto Ken","CK",false,function(on)Cb.tg.K=on fire("Combat","Ken",{enable=on})end,o);o=o+1 mkTg("Auto Attack","CA",false,function(on)Cb.tg.A=on if on then cGo()else cStop()end end,o)end
TBU["Boss"]=function()secL("Boss",1)mkDd("Select Boss",D.Bosses,function(v)S.Boss=v fire("Boss","select",{boss=v})Nf.Push("INFO","Boss",v,2)end,2,"Boss")mkBt("Update Boss List",function()fire("Boss","updateList",{})Nf.Push("SUCCESS","Boss","Updated",2)end,3)secL("Boss Combat",10)mkTg("Auto Kill Selected Boss","AKB",false,function(on)fire("Boss",on and"killSelected"or"stop",{boss=S.Boss,enable=on})end,11)mkTg("Auto Farm All Bosses","AFAB",false,function(on)fire("Boss",on and"farmAll"or"stop",{enable=on})end,12)mkTg("Take Boss Quest","TBQ",false,function(on)fire("Boss",on and"takeQuest"or"stop",{enable=on})end,13)end
TBU["Material"]=function()secL("Material",1)local mn={"Select Material..."}for n in pairs(D.Mat)do table.insert(mn,n)end table.sort(mn)mkDd("Select Material",mn,function(v)if v=="Select Material..."then return end S.Mat=v local i=D.Mat[v]if i then Nf.Push("SUCCESS","Material",v.." @ "..i[2],4)fire("Material","select",{material=v,npc=i[1],island=i[2],sea=i[3],drop=i[4],lv=i[5]})end TBU["Material"]()end,2,"Mat")secL("Info",10)local ip=mkI(11,110)if S.Mat then local i=D.Mat[S.Mat]if i then fI(ip,{"Material : "..S.Mat,"NPC      : "..i[1],"Island   : "..i[2].." (Sea "..i[3]..")","Drop     : "..i[4],"Req Lv   : "..i[5]})end else fI(ip,{"Pilih material."})end secL("Auto Farm",20)mkTg("Auto Farm Material","AFM",false,function(on)fire("Material",on and"start"or"stop",{material=S.Mat,enable=on})end,21)mkTg("Stop When Obtained","MSO",false,function(on)fire("Material","stopWhenObtained",{enable=on})end,22)end
TBU["Sea"]=function()secL("Sea Config",1)mkDd("Select Sea",{"Sea 1","Sea 2","Sea 3"},function(v)S.Sea=tonumber(v:match("%d+"))or 1 TBU["Sea"]()end,2,"Sea")local cs=S.Sea or 1 local ml={"Select Sea Mob..."}for _,m in ipairs(D.SeaMobs)do if m.s==cs then table.insert(ml,m.n.." ("..m.t.." · "..m.hp.." HP)")end end if #ml==1 then ml={"(No mob)"}end mkDd("Enemies [Select]",ml,function(v)if v=="Select Sea Mob..."or v=="(No mob)"then return end S.SeaMob=v local nm=v:match("^(.-) %(")Nf.Push("INFO","Sea Mob",nm or v,3)fire("Sea","selectMob",{mob=nm or v,sea=cs})end,3,"SeaMob")secL("Sea Farm",10)mkTg("Auto Farm Sea","AFS",false,function(on)fire("Sea",on and"farm"or"stop",{enable=on,mob=S.SeaMob,sea=cs})end,11)mkTg("Auto Destroy Boats","ADB",false,function(on)fire("Sea",on and"start"or"stop",{mode="boats",enable=on})end,12)mkTg("Auto Destroy Sea Beast","ADS",false,function(on)fire("Sea",on and"start"or"stop",{mode="seabeast",enable=on})end,13)mkTg("Auto Hunt Leviathan","AHL",false,function(on)fire("Sea",on and"start"or"stop",{mode="leviathan",enable=on})end,14)mkTg("Buy Boat","BB",false,function(on)fire("Sea",on and"start"or"stop",{mode="buyBoat",enable=on})end,15)mkTg("Auto No-Clip Boat","NCB",false,function(on)fire("Sea",on and"start"or"stop",{mode="noclip",enable=on})end,16)mkTg("Auto Destroy Rocks","ADR",false,function(on)fire("Sea",on and"start"or"stop",{mode="rocks",enable=on})end,17)mkSl("Boat Height",0,100,10,function(v)fire("Sea","boatHeight",{value=v})end,18)mkSl("Boat Speed",0,200,50,function(v)fire("Sea","boatSpeed",{value=v})end,19)end
TBU["Quests / Items"]=function()secL("Secret Quest (Sea 1)",1)if S.Sea~=1 then U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamMedium,Text="Secret Quest hanya di Sea 1.",TextColor3=T.Wn,TextSize=12,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,40)},CS).LayoutOrder=2 else local iS={}for _,q in ipairs(D.SQ)do iS[q.i]=true end local iL={"All Islands"}for n in pairs(iS)do table.insert(iL,n)end table.sort(iL)mkDd("Select Island",iL,function(v)S.SQI=(v=="All Islands")and nil or v TBU["Quests / Items"]()end,2,"SQI")local sel=S.SQI or"All Islands"local ql={"Select Quest..."}local qm={}for _,q in ipairs(D.SQ)do if sel=="All Islands"or q.i==sel then local lb=q.n.." @"..q.i table.insert(ql,lb)qm[lb]=q end end if #ql==1 then ql={"(Kosong)"}end mkDd("Select Quest",ql,function(v)if v=="Select Quest..."or v=="(Kosong)"then return end local q=qm[v]if q then S.SQ=q.n S.SQI=q.i Nf.Push("INFO","Secret",q.n,4)fire("Quest","selectSecret",{name=q.n,island=q.i})end end,3,"SQ")mkBt("Start Selected Quest",function()if not S.SQ then Nf.Push("WARNING","Quest","Pilih dulu",2)return end fire("Quest","startSecret",{name=S.SQ,island=S.SQI})Nf.Push("INFO","Secret","Mulai: "..S.SQ,3)end,4)mkBt("Stop Auto Secret",function()fire("Quest","stopSecret",{})end,5)end secL("Boss Special",20)local o=21 local function bb(n,a)mkBt(n,function()fire("Quest",a,{enable=true})Nf.Push("INFO",n,"Started",2)end,o)o=o+1 end bb("Kill Cake Prince","killCakePrince")bb("Auto Spawn & Kill Dough King","spawnDoughKing")bb("Kill Soul Reaper","killSoulReaper")bb("Auto Spawn & Kill rip_indra","spawnIndra")secL("Weapon Grind",o);o=o+1 local function ib(n,a)mkBt(n,function()fire("Quest",a,{enable=true})Nf.Push("INFO",n,"Started",2)end,o)o=o+1 end ib("Auto Get Yama","getYama")ib("Auto Get Tushita","getTushita")ib("Auto Get Buddy Sword","getBuddySword")ib("Auto Get Soul Guitar","getSoulGuitar")ib("Auto Get Hallow Scythe","getHallowScythe")end
TBU["Fruit / Raid"]=function()
secL("Raid",1)
mkDd("Select Chip",D.Chips,function(v)S.Chip=v fire("Raid","selectChip",{chip=v})end,2,"Chip")
mkBt("Start Raid",function()fire("Raid","start",{})end,3)
mkTg("AutoKillRaid","AKR",false,function(on)fire("Raid",on and"start"or"stop",{enable=on})end,4)
secL("Fruit Roll",10)
mkBt("Rolled Fruit (1x)",function()fire("Raid","rolled",{amount=1})end,11)
mkBt("Rolled Fruit (10x)",function()fire("Raid","rolled",{amount=10})end,12)
local lastRoll=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Last Roll: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)lastRoll.LayoutOrder=13
local rollCount=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Total Rolls: 0",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)rollCount.LayoutOrder=14
local rr=R("Raid")if rr then CM:add(rr.OnClientEvent:Connect(function(k,d)if k=="rolled"then lastRoll.Text="Last Roll: "..tostring(d.name or d)elseif k=="rollCount"then rollCount.Text="Total Rolls: "..tostring(d)end end))end
secL("Fruit Store",20)
mkTg("Auto Store Fruit","ASF",false,function(on)
if on then
local function storeAll()
local ch=Plr.Character if not ch then return end
for _,t in ipairs(ch:GetChildren())do if t:IsA("Tool")and string.find(string.lower(t.Name),"fruit")then fire("Fruit","store",{item=t.Name,from="character"})Nf.Push("SUCCESS","Stored",t.Name,1.5)task.wait(0.3)end end
local bp=Plr:FindFirstChild("Backpack")if bp then for _,t in ipairs(bp:GetChildren())do if t:IsA("Tool")and string.find(string.lower(t.Name),"fruit")then fire("Fruit","store",{item=t.Name,from="backpack"})Nf.Push("SUCCESS","Stored",t.Name,1.5)task.wait(0.3)end end end
end
task.spawn(function()while S.Tg.ASF do U.tr(storeAll)task.wait(5)end end)
Nf.Push("SUCCESS","Auto Store","ON",2)
else fire("Fruit","store_stop",{})Nf.Push("INFO","Auto Store","OFF",2)end
end,21)
mkTg("Tween Fruit [Smooth]","TweenF",false,function(on)
if on then
local function tweenStore()
local ch=Plr.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")then return end
local hrp=ch.HumanoidRootPart
local function anim(tool)
local cl=tool:Clone()cl.Parent=workspace
local h=cl:IsA("Tool")and cl:FindFirstChild("Handle")or cl
if h and h:IsA("BasePart")then h.CanCollide=false h.Anchored=true h.CFrame=hrp.CFrame*CFrame.new(0,-1,-1)
local tw=Tw:Create(h,TweenInfo.new(0.4,Enum.EasingStyle.Quart,Enum.EasingDirection.Out),{CFrame=hrp.CFrame*CFrame.new(0,5,0)})tw:Play()tw.Completed:Wait()end
cl:Destroy()
end
for _,t in ipairs(ch:GetChildren())do if t:IsA("Tool")and string.find(string.lower(t.Name),"fruit")then anim(t)fire("Fruit","store",{item=t.Name,from="character"})Nf.Push("SUCCESS","Tween Stored",t.Name,1.5)task.wait(0.5)end end
local bp=Plr:FindFirstChild("Backpack")if bp then for _,t in ipairs(bp:GetChildren())do if t:IsA("Tool")and string.find(string.lower(t.Name),"fruit")then anim(t)fire("Fruit","store",{item=t.Name,from="backpack"})Nf.Push("SUCCESS","Tween Stored",t.Name,1.5)task.wait(0.5)end end end
end
task.spawn(function()while S.Tg.TweenF do U.tr(tweenStore)task.wait(5)end end)
Nf.Push("SUCCESS","Tween Fruit","ON",2)
else Nf.Push("INFO","Tween Fruit","OFF",2)end
end,22)
end
TBU["Fishing"]=function()secL("Fishing",1)mkTg("Auto Fish","AF",false,function(on)fire("Fishing",on and"start"or"stop",{enable=on})end,2)mkTg("Auto Cast","ACa",false,function(on)fire("Fishing",on and"start"or"stop",{mode="cast",enable=on})end,3)end
TBU["Status"]=function()secL("Server Status",1)local fl=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Fruit Spawn: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)fl.LayoutOrder=2 local ml=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Map Check: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)ml.LayoutOrder=3 local tl=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Server Time: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)tl.LayoutOrder=4 mkBt("Check Entire Map",function()fire("Misc","checkMap",{})end,5)local sr=R("Misc")if sr then CM:add(sr.OnClientEvent:Connect(function(k,d)if k=="fruitStatus"then fl.Text="Fruit Spawn: "..(d and"Yes"or"No")elseif k=="mapStatus"then ml.Text="Map Check: "..tostring(d)end end))end task.spawn(function()while Gui.Parent do tl.Text="Server Time: "..os.date("%H:%M:%S")task.wait(1)end end)end
TBU["PvP"]=function()secL("PvP",1)local pn={"None"}for _,p in ipairs(Players:GetPlayers())do if p~=Plr then table.insert(pn,p.Name)end end mkDd("Select Player",pn,function(v)S.Plr=v if v~="None"then aimTarget=v end fire("PvP","select",{player=v})end,2,"Plr")mkTg("Aimbot (Smooth Cam)","Aim",false,function(on)aimOn=on if on then aimTarget=S.Plr Nf.Push("SUCCESS","Aimbot",S.Plr or"None",2)else Nf.Push("INFO","Aimbot","OFF",2)end end,3)mkTg("Auto Attack Target","AAT",false,function(on)fire("PvP",on and"start"or"stop",{enable=on,target=S.Plr})end,4)mkBt("Teleport to Player",function()fire("PvP","teleport",{player=S.Plr})end,5)mkTg("Auto Skill","ASk",false,function(on)fire("PvP",on and"start"or"stop",{enable=on})end,6)end
TBU["Stats"]=function()secL("Stat Allocation",1)mkTg("Start Add Stats","SAS",false,function(on)fire("Stats",on and"start"or"stop",{enable=on})end,2)mkSl("Melee",0,100,0,function(v)fire("Stats","melee",{value=v})end,3)mkSl("Sword",0,100,0,function(v)fire("Stats","sword",{value=v})end,4)mkSl("Gun",0,100,0,function(v)fire("Stats","gun",{value=v})end,5)mkSl("Defense",0,100,0,function(v)fire("Stats","defense",{value=v})end,6)mkSl("Blox Fruit %",0,100,0,function(v)fire("Stats","fruit",{value=v})end,7)end
TBU["Misc"]=function()secL("Server",1)U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="Job ID: "..game.JobId,TextColor3=T.Tx,TextSize=12,TextXAlignment=Enum.TextXAlignment.Left,TextWrapped=true,Size=UDim2.new(1,-8,0,32)},CS).LayoutOrder=2 mkBt("Copy Job ID",function()if setclipboard then pcall(setclipboard,game.JobId)end Nf.Push("SUCCESS","Job ID","Copied",2)end,3)local jb=U.mk("TextBox",{BackgroundColor3=T.Bg2,BorderSizePixel=0,ClearTextOnFocus=false,PlaceholderText="Enter Job ID",PlaceholderColor3=T.Tx2,TextColor3=T.Tx,Font=Enum.Font.Gotham,TextSize=12,Text="",Size=UDim2.new(1,-8,0,30)},CS)U.cr(jb,6)U.st(jb)jb.LayoutOrder=4 mkBt("Join Job ID",function()local id=jb.Text if id and #id>=8 then pcall(function()TS:TeleportToPlaceInstance(game.PlaceId,id,Plr)end)end end,5)secL("Utility",10)mkBt("Redeem All Code",function()Nf.Push("INFO","Redeem","Kirim "..#D.Codes,3)for i,c in ipairs(D.Codes)do fire("Misc","redeem",{code=c})Nf.Push("INFO","Redeem "..i.."/"..#D.Codes,c,1.5)task.wait(0.8)end Nf.Push("SUCCESS","Redeem","Selesai",4)end,11)mkTg("Anti AFK","AAF",false,function(on)fire("Misc",on and"start"or"stop",{enable=on})end,12)mkTg("No Clip","NC",false,function(on)fire("Misc",on and"start"or"stop",{mode="noclip",enable=on})end,13)mkTg("Infinite Jump","IJ",false,function(on)fire("Misc",on and"start"or"stop",{mode="infjump",enable=on})end,14)mkTg("Auto Attack","AAM",false,function(on)fire("Combat","Attack",{enable=on})Cb.tg.A=on if on then cGo()else cStop()end end,15)local fp=U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.Gotham,Text="FPS: -",TextColor3=T.Tx,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,20)},CS)fp.LayoutOrder=16 local fr,ls=0,tick()CM:add(RunSvc.RenderStepped:Connect(function()fr=fr+1 if tick()-ls>=1 then fp.Text="FPS: "..fr fr=0 ls=tick()end end))end
local TAB_FEAT={Discord={"Join Discord","Version","Copy Asset"},Farm={"Select Tool","UI Scale","Auto Farm Level","Auto Farm Nearest","Auto Factory","Auto Farm Ectoplasm","Auto Accept Quest","Auto Farm Chest","Stop When Get Item in Chest","Max Chest Range","Farm Speed","Auto Haki","Auto Ken","Auto Attack"},Boss={"Select Boss","Update Boss List","Auto Kill Selected Boss","Auto Farm All Bosses","Take Boss Quest"},Material={"Select Material","Auto Farm Material","Stop When Obtained"},Sea={"Select Sea","Enemies","Auto Farm Sea","Auto Destroy Boats","Auto Destroy Sea Beast","Auto Hunt Leviathan","Buy Boat","Auto No-Clip Boat","Auto Destroy Rocks","Boat Height","Boat Speed"},["Quests / Items"]={"Secret Quest","Select Island","Select Quest","Start Selected Quest","Kill Cake Prince","Dough King","Soul Reaper","rip_indra","Yama","Tushita","Buddy Sword","Soul Guitar","Hallow Scythe"},["Fruit / Raid"]={"Select Chip","Start Raid","AutoKillRaid","Rolled Fruit 1x","Rolled Fruit 10x","Auto Store Fruit","Tween Fruit"},Fishing={"Auto Fish","Auto Cast"},Status={"Fruit Spawn","Map Check","Server Time"},PvP={"Select Player","Aimbot","Auto Attack Target","Teleport","Auto Skill"},Stats={"Start Add Stats","Melee","Sword","Gun","Defense","Blox Fruit"},Misc={"Copy Job ID","Join Job ID","Redeem All Code","Anti AFK","No Clip","Infinite Jump","Auto Attack","FPS"}}
local oT
oT=function(n)cT=n clrC()if TBU[n]then U.tr(TBU[n],function(e)Nf.Push("ERROR","Tab",tostring(e),3)end)end for _,b in ipairs(SSb:GetChildren())do if b:IsA("TextButton")then local a=(b.Name=="Tab_"..n)U.tn(b,TweenInfo.new(0.15),{BackgroundColor3=a and T.Pr or T.Bg2,TextColor3=a and T.Tx or T.Tx2})end end end
for i,t in ipairs(CFG.Tabs)do local b=U.mk("TextButton",{Name="Tab_"..t,BackgroundColor3=T.Bg2,BorderSizePixel=0,Text="  "..t,TextColor3=T.Tx2,Font=Enum.Font.GothamMedium,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,AutoButtonColor=false,Size=UDim2.new(1,-4,0,34)},SSb)b.LayoutOrder=i U.cr(b,6)b.MouseEnter:Connect(function()if cT~=t then U.tn(b,TweenInfo.new(0.12),{BackgroundColor3=T.Pn})end end)b.MouseLeave:Connect(function()if cT~=t then U.tn(b,TweenInfo.new(0.12),{BackgroundColor3=T.Bg2})end end)b.MouseButton1Click:Connect(function()oT(t)end)end
oT("Discord")
local sRes=nil
SR:GetPropertyChangedSignal("Text"):Connect(function()
local q=string.lower(SR.Text)
if q==""then if sRes then sRes:Destroy()sRes=nil end if cT then oT(cT)end return end
if sRes then sRes:Destroy()end
sRes=U.mk("Frame",{BackgroundColor3=T.Bg2,BorderSizePixel=0,Size=UDim2.new(1,-16,1,-60),Position=UDim2.new(0,8,0,54),ZIndex=5},Ct)U.cr(sRes,8)U.st(sRes,T.Pr)
U.mk("UIListLayout",{Padding=UDim.new(0,4),SortOrder=Enum.SortOrder.LayoutOrder},sRes)U.pd(sRes,8)
local found={}
for tn,fs in pairs(TAB_FEAT)do for _,fn in ipairs(fs)do if string.find(string.lower(fn),q,1,true)or string.find(string.lower(tn),q,1,true)then table.insert(found,{tab=tn,f=fn})end end end
if #found==0 then U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text="Feature not found: \""..SR.Text.."\"",TextColor3=T.Er,TextSize=13,Size=UDim2.new(1,-8,0,30),LayoutOrder=1},sRes)return end
U.mk("TextLabel",{BackgroundTransparency=1,Font=Enum.Font.GothamBold,Text="Found "..#found.." result(s):",TextColor3=T.PrL,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,Size=UDim2.new(1,-8,0,24),LayoutOrder=0},sRes)
for i,r in ipairs(found)do local btn=U.mk("TextButton",{BackgroundColor3=T.Pn,BorderSizePixel=0,Text="  ▸ ["..r.tab.."]  "..r.f,TextColor3=T.Tx,Font=Enum.Font.GothamMedium,TextSize=13,TextXAlignment=Enum.TextXAlignment.Left,AutoButtonColor=false,Size=UDim2.new(1,-8,0,32),LayoutOrder=i},sRes)U.cr(btn,6)U.st(btn)btn.MouseEnter:Connect(function()U.tn(btn,TweenInfo.new(0.12),{BackgroundColor3=T.Pn2})end)btn.MouseLeave:Connect(function()U.tn(btn,TweenInfo.new(0.12),{BackgroundColor3=T.Pn})end)btn.MouseButton1Click:Connect(function()SR.Text=""oT(r.tab)end)end
end)
local isO=true
local function setW(op)isO=op U.tn(M,TweenInfo.new(0.28,Enum.EasingStyle.Quart),{Size=op and UDim2.fromOffset(CFG.W,CFG.H)or UDim2.fromOffset(0,0)})end
Ob.MouseButton1Click:Connect(function()if isO then setW(false)else setW(true)end end)
ClsBtn.MouseButton1Click:Connect(function()setW(false)end)
MinBtn.MouseButton1Click:Connect(function()setW(false)end)
local si=3 ScaleBtn.MouseButton1Click:Connect(function()si=si%#CFG.SO+1 Sc.Scale=CFG.SO[si]Nf.Push("INFO","UI Scale",tostring(math.floor(CFG.SO[si]*100)).."%",1.5)end)
do local d,sP,st TB.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d=true sP=i.Position st=M.Position end end)UIS.InputChanged:Connect(function(i)if not d then return end if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then local dl=i.Position-sP M.Position=UDim2.new(st.X.Scale,st.X.Offset+dl.X,st.Y.Scale,st.Y.Offset+dl.Y)end end)UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d=false end end)end
do local d,sP,st Ob.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d=true sP=i.Position st=Ob.Position end end)UIS.InputChanged:Connect(function(i)if not d then return end if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then local dl=i.Position-sP Ob.Position=UDim2.new(st.X.Scale,st.X.Offset+dl.X,st.Y.Scale,st.Y.Offset+dl.Y)end end)UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d=false end end)end
if UIS.TouchEnabled then SSb.ScrollingDirection=Enum.ScrollingDirection.Y CS.ScrollingDirection=Enum.ScrollingDirection.Y end
Plr.CharacterRemoving:Connect(function()cStop()end)
Nf.Push("SUCCESS","SysxHub","Loaded v"..Br.Ver,3)
end
